<a href="https://colab.research.google.com/github/gmanojkumar402-max/Manoj-colab-notebooks/blob/main/DS_python_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
# Basic function creation
def manoj():
  print("good boy")
manoj()

good boy

In [128]:
# creating 2 functions in a single python program
# Ex: 1
def manoj():
  print("boy friend of priya")
def priya():
  print("girlfriend of manoj")
manoj()
priya()

boy friend of priya
girlfriend of manoj

In [129]:
# creating 2 functions in a single python program
# Ex: 2
def manoj():
  print("brother of vinay")
def vinay():
  print("brother of manoj")
manoj()
vinay()

brother of vinay
brother of manoj

In [130]:
# One function can call another function
def manoj():
  print("good boy")
  vinay()
def vinay():
  print("also a good boy")
manoj()

good boy
also a good boy

In [131]:
def m1():
  print("first function")
  m2()
def m2():
  print("second function")
m1()

first function
second function

# Functions 2 types
# parameterised functions
# No parameterised functions

In [132]:
# No parameterised functions
def manoj():
  print("good boy")
manoj()

good boy

In [133]:
# parameterised functions help to process the function operations
def manoj(a):
  print("single paraeterised function:", a)
manoj(10)

single paraeterised function: 10

In [134]:
def manoj(a):
  print("single parameterised function:", a)
manoj("good boy")

single parameterised function: good boy

In [135]:
def manoj(a):
  print("single parameterised function:", a)
x = input("Enter a Value:")
manoj(x)

Enter a Value:1
single parameterised function: 1

In [136]:
# Two parameterised function
def manoj(a,b):
  print("Two parameterised function:", a+b)
manoj(10,20)

Two parameterised function: 30

In [137]:
# Two parameterised function
def manoj(a,b):
  print("Two parameterised function:", a,b)
manoj(10,20)

Two parameterised function: 10 20

return keyword in python

# Based on return statement
# Function without return statement
# Function with return statement

In [138]:
# Function without return statment
def manoj():
  print("good boy")
manoj()

good boy

In [139]:
# print is a pre-defined function which can be called any where
print("Hello world")

Hello world

In [140]:
# return cannot be called outside a function
return 100

SyntaxError: 'return' outside function (ipython-input-3481587031.py, line 2)

In [141]:
# Function with return statment
def manoj():
  print("good boy")
  return 100
manoj()

good boy

100

# function calling we need to assign it to a variable when function contains return statement

In [142]:
def manoj():
  print("bank balance is")
  return 100
m = manoj()
print(m)

bank balance is
100

When we assign a variable to the function calling then that variable can be used it further

In [143]:
def balance():
  return -1
b = balance()

if b == 0:
  print("Balance is:", b)
elif b<0:
  print("balance is:", b, 'negative please deposit')
else:
  print("Balance:", b)

balance is: -1 negative please deposit

In [144]:
def balance():
  return 100
b = balance()
if b < 50:
  print("balance is less than:", 50)
elif b>50:
  print("balance is greator than:", 50)
  if b==100:
    print("balance is equal to:", 100)

balance is greator than: 50
balance is equal to: 100

In [145]:
# valid but not recommended
def manoj():
  print("good boy")
  return 100
print(manoj())

good boy
100

When no return statment in the function the default return value is NONE

In [146]:
def manoj():
  print(input("Enter value or text:",))
m = manoj()
print(m)

Enter value or text:1
1
None

Function can return multiple values

In [147]:
def manoj():
  print("good boy")
  a = 10
  b = 20
  return a,b
m,n = manoj()
print("first value is:",m)
print("first value is:",n)

good boy
first value is: 10
first value is: 20

In [148]:
def manoj():
  print("good boy")
  a = input("enter value:",)
  b = input("enter value:",)
  c = input("enter value:",)
  return a,b,c
x,y,z = manoj()
print("first value:",x)
print("second value:",y)
print("third value:",z)

good boy
enter value:1
enter value:2
enter value:3
first value: 1
second value: 2
third value: 3

Function returning multiple variables and while calling if we assign one variable then all values will be stored in tuple

In [149]:
def manoj():
  print("good boy")
  a = 10
  b = 20
  c = 30
  return a,b,c
x = manoj()
print(x)

good boy
(10, 20, 30)

In [150]:
def manoj(a,b,c):
  print("good boy")
  return a,b,c
x = manoj(10,20,30)
print(x)

good boy
(10, 20, 30)

In [151]:
def manoj(a,b,c):
  print("good boy")
  return a+b+c
x = manoj(10,20,30)
print(x)

good boy
60

parameters also called as formal arguments
While calling the function we should pass values or data to the function called as actual arguments

In [152]:
def manoj(a,b):
  print("good boy")
  c = a + b
  print(c)
x = 10
y = 20
manoj(x,y)
# a and b are formal arguments and x and y are actual arguments

good boy
30

In [153]:
def manoj(a):
  print("good boy")
  print("single parameterised function:", a)
x = 10
manoj(x)
# a is the formal argument and x is the actual argument

good boy
single parameterised function: 10

4 Types of argumet:

# positional arguments,
# keyword arguments(*args),
# default arguments,
# variable length arguments

In [154]:
# positional argument
def manoj(a,b):
  print(a + b)
manoj(1,2)

3

In [155]:
# key word argument
def manoj(a,b):
  print(a+b)
manoj(a = 1, b = 2)

3

In [156]:
def manoj(product,price):
  print("product is:",product,"and its price is:",price)
manoj(product = "pen", price = 100)

product is: pen and its price is: 100

In [157]:
def cart(product, price):
  print("product is:",product)
  print("price of the product is:",price)
cart(product = "shirt", price = 1000)

product is: shirt
price of the product is: 1000

In [158]:
# Default argument
def manoj(product = "shirt", price = 1000):
  print("product is:", product)
  print("price is:", price)
manoj()

product is: shirt
price is: 1000

positional argument should follow keyword argument

In [159]:
def cart(price, product = 'shirt'):
  print("product is:", product)
  print("price is:", price)
cart(price = 100)

product is: shirt
price is: 100

In [160]:
def cart(product, price = 40):
  print("product is:", product)
  print("price is:", price)
cart(product = "shirt", price = 1000)

product is: shirt
price is: 1000

# variable length arguments or *args
# If we define one parameterised function then during function calling
# we need to pass one value.
#Internally the provided values will be stored in tuple.

In [161]:
# variable length argument
def manoj(x):
  print(x)
manoj(10)

10

In [162]:
def manoj(x):
  print(x)
manoj(10,20)

TypeError: manoj() takes 1 positional argument but 2 were given

In [163]:
def manoj(*x):
  print(x)
manoj(10,20)

(10, 20)

Lambda function or anonymous function:
# lambda argument_list:expression

In [164]:
van = lambda a:a+a
X = van(5)
print(X)

10

In [165]:
# lambda function dont need a return function
can = lambda a,b: a + b
x = can(10,20)
print(x)

30

where does lambda function fits exactly

while passing a function as an argument to another function
# map(p1, p2)function
# filter(p1, p2)function
# reduce(p1, p2)function

# map is a predefined function it takes iterable and apply logic on every item and return iterable

In [166]:
# map function
without_gst_cost = [100,200,300,400]
with_gst_cost = map(lambda x:x+10, without_gst_cost)
x = list(with_gst_cost)
print("without GST item cost:", without_gst_cost)
print("with GST cost",x)

without GST item cost: [100, 200, 300, 400]
with GST cost [110, 210, 310, 410]

In [167]:
cost_of_two_item =[20,30]
cost_of_the_items_after_adding_profit =map(lambda x: x +10,cost_of_two_item)
y = list(cost_of_the_items_after_adding_profit)
print("cost_of_two_item:", cost_of_two_item)
print("cost_of_the_items_after_adding_profit:", cost_of_the_items_after_adding_profit)

cost_of_two_item: [20, 30]
cost_of_the_items_after_adding_profit: <map object at 0x7ef755a77ac0>

In [168]:
cost_of_two_item =[20,30]
cost_of_the_items_after_adding_profit =map(lambda x: x +10,cost_of_two_item)
y = list(cost_of_the_items_after_adding_profit)
print("cost_of_two_item:", cost_of_two_item)
print("cost_of_the_items_after_adding_profit:", y)

cost_of_two_item: [20, 30]
cost_of_the_items_after_adding_profit: [30, 40]

In [169]:
# filter(p1,p2)function. it has same properties as map
items_cost = [1,2,3,4,5,6]
gt_num = filter(lambda x : x > 4, items_cost)
y = list(gt_num)
print("items_cost:", items_cost)
print("eligible for discount:",y)

items_cost: [1, 2, 3, 4, 5, 6]
eligible for discount: [5, 6]

reduce(p1,p2) function
#This function apply a function of two arguments cumulatively to the items of sequence, from left to right.
# Finally this function reduce the sequence to a single value.

In [170]:
# reduce(p1, p2) function
from functools import reduce
items_cost = [1,2,3,4,5]
total_cost = reduce(lambda x,y: x+y, items_cost)
print("items_cost:", items_cost)
print("total_cost:", total_cost)

items_cost: [1, 2, 3, 4, 5]
total_cost: 15

# functions with data structure

In [178]:
# List
def square_numbers(nums):
  return [x**2 for x in nums]
s = square_numbers([1,2,3])
print(s)

[1, 4, 9]

In [179]:
# List
def manoj(nums):
  return [x*2 for x in nums]
m = manoj([1,2,3])
print(m)

[2, 4, 6]

In [177]:
def avg_scores(scores):
  return sum(scores.values())/len(scores)
a = avg_scores({"math": 90, "science":65})
print(a)

77.5

In [181]:
def add_bonus(salaries, bonus):
  return [s + bonus for s in salaries]
a = add_bonus([1000, 2000], 200)
print(a)

[1200, 2200]

# Functions with NumPy / Pandas style operations

In [233]:
# numeric scale
import pandas as pd
import numpy as np

data = {
    "name": ["A", "B", "C", "D"],
    "age": [22, 17, 35, 29],
    "salary": [30000, 15000, 50000, 40000]
}

df = pd.DataFrame(data)
df

def min_max_scale(series):
  """
  Scale values in a series to between 0 and 1.
  """
  return (series - series.min())/(series.max() - series.min())
df["salary_scaled"] = min_max_scale(df["salary"])
df

  name  age  salary  salary_scaled
0    A   22   30000       0.428571
1    B   17   15000       0.000000
2    C   35   50000       1.000000
3    D   29   40000       0.714286

In [191]:
# row-wise logic
def label_age(age):
  if age< 18:
    return "minor"
  elif age < 30:
    return "young"
  else:
    return "adult"
df["age_group"] = df["age"].apply(label_age)
df

  name  age  salary  salary_scaled age_group
0    A   22   30000       0.428571     young
1    B   17   15000       0.000000     minor
2    C   35   50000       1.000000     adult
3    D   29   40000       0.714286     young

In [193]:
# Function to filter data safely
def filter_high_salary(df, threshold):
  return df[df["salary"]> threshold]
high_salary_df = filter_high_salary(df, 30000)
high_salary_df

  name  age  salary  salary_scaled age_group
2    C   35   50000       1.000000     adult
3    D   29   40000       0.714286     young

In [196]:
# Function with NumPy logic
def log_transformation(series):
  return np.log(series)
df["log_salary"] = log_transformation(df["salary"])
df

  name  age  salary  salary_scaled age_group  log_salary
0    A   22   30000       0.428571     young   10.308953
1    B   17   15000       0.000000     minor    9.615805
2    C   35   50000       1.000000     adult   10.819778
3    D   29   40000       0.714286     young   10.596635

In [198]:
# Small functional pipeline (real DS flow)
def clean_salary(df):
  return df[df["salary"]>0]
def add_log_salary(df):
  df = df.copy()
  df["log_salary"] = np.log(df["salary"])
  return df
df_pipeline = add_log_salary(clean_salary(df))
df_pipeline

  name  age  salary  salary_scaled age_group  log_salary
0    A   22   30000       0.428571     young   10.308953
1    B   17   15000       0.000000     minor    9.615805
2    C   35   50000       1.000000     adult   10.819778
3    D   29   40000       0.714286     young   10.596635

In [199]:
# Scope & lifetime of variables
x = 10
def change():
  x = 20     # loacl
  return x
c = change()
print(c)

20

In [200]:
# global remains unchanged
x = 5
def compute():
  return x +10
c = compute()
print(c)

15

In [201]:
# avoiding globals(best practice)
def compute(x):
  return x + 10
c = compute(5)
print(c)

15

In [206]:
# Example 1: safe division
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None
safe_divide(5,6)

0.8333333333333334

In [216]:
# Example 1: safe division
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None
s = safe_divide(5,0)
print(s)

None

In [203]:
# missing value handling
def to_int(x):
  try:
    return int(x)
  except:
    return 0
to_int("manoj")

0

In [204]:
# missing value handling
def to_int(x):
  try:
    return int(x)
  except:
    return 0
to_int(1)

1

In [225]:
# validating input
def mean(nums):
  for x in nums:
    if not  isinstance(x, (int, float)):
      return 0
  return sum(nums)/len(nums)
m = mean([5,'a',3])
print(m)

0

In [226]:
# this code works only for empty list
def mean(nums):
    if not nums:
        return 0
    return sum(nums) / len(nums)
m = mean([])
print(m)

0

Docstrings & readable functions

In [228]:
# simple docstring
def calc_mean(nums):
  """
  Calculate the mean of a list of numbers.
  """
  return sum(nums)/len(nums)
calc_mean([1,2,3])

2.0

Small functional pipelines (VERY IMPORTANT)

In [234]:
# simple pipeline
def clean(data):
  return  [x for x in data if x is not None]
def square(data):
  return [x**2 for x in data]
c = square(clean([1, None, 2, 3]))
print(c)

[1, 4, 9]

In [236]:
# feature pipeline
def add_tax(price):
  return price * 1.05
def discount(price):
  return price * 0.9
x = discount(add_tax(100))
print(x)

94.5

In [242]:
# EDA-style pipeline
def remove_negatives(nums):
  return [x for x in nums if x >=0]
def avg(nums):
  return sum(nums)/len(nums)
x = avg(remove_negatives([1,2,3,4,-5]))
print(x)

2.5

In [243]:
def remove_negatives(nums):
    return [x for x in nums if x >= 0]

def avg(nums):
    return sum(nums) / len(nums)

x = avg(remove_negatives([10, -5, 20]))
print(x)

15.0