<a href="https://colab.research.google.com/github/gmanojkumar402-max/Manoj-colab-notebooks/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Featuring engineering --> Data Preperation

In feature engineering, we identify which features are important for predicting the target variable and which are not. For example, in predicting rice production, the area of land is an important feature, while the farmer's name is not relevant. Feature engineering also involves handling missing values, treating outliers, and transforming data to make it suitable for machine learning models.

Feature engineering is the process of selecting, transforming, and creating relevant features from raw data to improve model performance. It includes identifying important features, removing irrelevant ones, handling missing values and outliers, and transforming data into a suitable format.

In feature engineering, we often use libraries where we import classes, create objects, and call methods (especially in scikit-learn), but many operations can also be performed using functions without creating objects.

Feature scaling

10,         20,         30,         40,         50        
The difference between each value is 10 but when we consider the difference between 50 and 10 the difference is 40

Now if we want to represent all the above values between 0 - 1 divide all teh values with the max value 50


0.2,          0.4,          0.6,          0.8,         1

Now the difference between 1 and 0.2 is only 0.8

Now we have bought the difference from max number to min number from 40 to 0.8

So, scaling resizes the scale

This is called scaling

Set a particular range as mentioned above 0 – 1 and we can manipulate the date as done above.

Feature scaling is a data preprocessing technique used to normalize or standardize independent features so that they fall within a specific range. It ensures that all features contribute equally to the model and prevents bias due to differences in scale.

It is performed during the data pre-processing.

Data pre-processing

In machine learning data pre-processing is an important step

The purpose of this technique is cleaning and organizing the raw data to make it suitable for building and training machine learning models as real-world data is incomplete, inconsistent, inaccurate (contains errors or outliers), and often lacks specific attribute values/trends.

We deal with 2 types of data numerical and categorical data

Numerical --> int and float

categorical --> ordinal data which follows the order

Ex: small > medium > big

categorical --> Nominal data which do not follow the order

Ex: color: red , green, purple

city: vizag, new-york, chicago

we cannot compare values

How we handle it:

Using encoding (e.g., One-Hot Encoding in scikit-learn):

Color → Red, Blue, Green

Becomes:
Red   → [1,0,0]
Blue  → [0,1,0]
Green → [0,0,1]

Numerical data

Quantitative data is the measure of monthly sales, or student scores etc.

The natural way to represent these quantities is numerically (e.g., 29 students, $529,392 in sales).

Label Encoder

Using this we can convert categorical variables to be numeric.

converting a string data to numerical data is called as LabelEncoder

So now we need to take the categorical data, convert them into numbers and provide that number to the ML algorithm.

Ex: Male --> 0,  Female --> 1

feature engineering involves transforming raw data into meaningful features that can enhance the performance of machine learning models. This process includes creating new features, encoding categorical variables, handling missing data, scaling features, and selecting relevant variables.

1️⃣ Handling Missing Data

Missing values should be handled carefully rather than simply dropped.

Methods:

Mean / Median / Mode imputation

Forward/Backward fill

Advanced methods (KNN, model-based)

In pandas we drop or fill but in ML we prefer imputation

2️⃣Encoding Categorical Variables

Types:

Nominal → One-Hot Encoding

Ordinal → Label Encoding

Using scikit-learn

3️⃣ Feature Scaling

Scale features so they have comparable ranges

Methods:
Min-Max Scaling
Standardization (Z-score)

✔ Needed for:

SVM,
KNN,
Gradient-based models

4️⃣ Creating New Features

Examples:

Polynomial Features:create higher-degree terms to
capture non-linear relationships

Date-Time Features:break down date fields into components and extract
day, month, year, weekday to capture time related patterns

5️⃣ Dimensionality Reduction

Reduce number of features by projecting them onto new axes that explain most of the variance in the data while keeping important information.

Example:
PCA (Principal Component Analysis)

✔ Helps:

Reduce noise
Improve performance
Avoid overfitting

6️⃣ Interaction Features:
Create new features by combining existing ones, like multiplying, dividing, or adding features to capture relationships.

Examples:
area * rainfall,
price / quantity

This will often improves model performance significantly

In Ml a string is called as a label

In [6]:
# LabelEncoder
from sklearn.preprocessing import LabelEncoder
import pandas as pd
data = {'Company': ['Google','Twitter','Google','Linkedin'], 'Role': ['Data scientist','Sales manager','HR','HR']}
df = pd.DataFrame(data)
le = LabelEncoder()
df['Company_n'] = le.fit_transform(df['Company'])
df['Role_n'] = le.fit_transform(df['Role'])
print(df)

    Company            Role  Company_n  Role_n
0    Google  Data scientist          0       0
1   Twitter   Sales manager          2       2
2    Google              HR          0       1
3  Linkedin              HR          1       1

MinMaxScaler results in scaled data values that fall in the range 0 and 1.

IN ML whenever we are talking about X it is input and when ever we are talking about y it is output

In [14]:
# MinMaxScaler
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
data = {'X': [10,20,30,40,50], 'y': [25,50,75,100,125]}
df = pd.DataFrame(data)
MMS = MinMaxScaler(feature_range = (0,1))
df['new_X'] = MMS.fit_transform(df[['X']])
# minmaxscaler expects 2D array and the output is a 2D NumPy array.
# Shape → (5, 1)
df['new_X']

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
Name: new_X, dtype: float64

In [11]:
df.dtypes

X          int64
y          int64
new_X    float64
dtype: object

In [15]:
# Transforming features
# using FunctionTransformer we can transform the features.
import numpy as np
from sklearn.preprocessing import FunctionTransformer
b = [[10,20],[30,40],[50,60]]
a = np.array(b)
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [16]:
def add_ten(x):
  return x + 10
ft = FunctionTransformer(add_ten)
ft.transform(a)

array([[20, 30],
       [40, 50],
       [60, 70]])

Handling outlier: value which is very far from the common data is an outlier

outlier influence the model efficiency

Three ways to handle these,

Drop outlier or filter outlier

Marking them using boolean condition

Transform into feature

In [18]:
# A dataframe with outliers
import numpy as np
import pandas as pd
houses = pd.DataFrame()
houses['Prices'] = [534433, 392333, 293222, 4322032]
houses['rooms'] = [2, 3, 5, 100]
houses['sq_feet'] = [1500, 2500, 1500, 48000]
houses

    Prices  rooms  sq_feet
0   534433      2     1500
1   392333      3     2500
2   293222      5     1500
3  4322032    100    48000

In [19]:
# Filtering the outlier
houses['rooms'] < 20

0     True
1     True
2     True
3    False
Name: rooms, dtype: bool

In [20]:
houses[houses['rooms'] < 20]

   Prices  rooms  sq_feet
0  534433      2     1500
1  392333      3     2500
2  293222      5     1500

In [21]:
# Marking as outliers
houses['Outlier'] = np.where(houses['rooms'] < 20, 0, 1)
print(houses)

    Prices  rooms  sq_feet  Outlier
0   534433      2     1500        0
1   392333      3     2500        0
2   293222      5     1500        0
3  4322032    100    48000        1

where is a predefined function which is available in numpy which is taking 3 parameters.

If the condition value is true it assigns the value as 0 and if the condition value is false it assigns the value as 1

Impute Missing values

There are two types of missing values

Numeric missing values

Categorical missing values

We can impute missing numeric values with different strategies like mean, median, most_frequent, constant

Imputing missing values refers to the process of replacing missing or null values in a dataset with substitute values.

In [3]:
# Impute Missing values
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
students = [[85, 'M', 'verygood'],
[95, 'F', 'excellent'],
[60, None, 'good'],
[np.nan, 'M', 'average'],
[70, 'M', 'good'],
[np.nan, None, 'verygood'],
[60, 'F', 'verygood'],
[98, 'M', 'excellent']]
cols = ['Marks', 'Gender', 'Result']
df = pd.DataFrame(students, columns = cols)
print(df)

   Marks Gender     Result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

np.nan is commonly used to represent missing numerical values, while None is a Python object used to represent missing values in object or string data. In Pandas, both can be used, but np.nan is preferred for numerical operations.

In [9]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

The missing_values parameter specifies what constitutes a missing value in our dataset.

The strategy parameter defines how the missing values should be replaced

Note: imputer object works with single column array

In [10]:
# creating a single column array
df['Marks'] # This return a Series

0    85.0
1    95.0
2    60.0
3     NaN
4    70.0
5     NaN
6    60.0
7    98.0
Name: Marks, dtype: float64

In [11]:
df['Marks'].values # This returns a single row array

array([85., 95., 60., nan, 70., nan, 60., 98.])

In [12]:
# We don't need single row array. We need a single column array
# reshape method
df['Marks'].values.reshape(8,1)

array([[85.],
       [95.],
       [60.],
       [nan],
       [70.],
       [nan],
       [60.],
       [98.]])

In [13]:
# Now assigning a variable to a single column array
a = df['Marks'].values.reshape(8,1)
# we can even use the below syntax
a = df['Marks'].values.reshape(-1,1)
# -1 -1 tells NumPy to automatically calculate that dimension.

In [14]:
# changing the existing column data
df['Marks'] = imputer.fit_transform(a)
print(df)

   Marks Gender     Result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3   78.0      M    average
4   70.0      M       good
5   78.0   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

If there is no most frequent value then according to ascending order whatever is the 1st value that value will be considered.

In [16]:
# Imputing missing numeric values with most_frequent strategy
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
[85, 'M', 'verygood'],
[95, 'F', 'excellent'],
[60, None, 'good'],
[np.nan, 'M', 'average'],
[70, 'M', 'good'],
[np.nan, None, 'verygood'],
[60, 'F', 'verygood'],
[98, 'M', 'excellent']
]
cols = ['Marks','G','result']
df = pd.DataFrame(students, columns = cols)
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
a = df['Marks'].values.reshape(-1,1)
df['Marks'] = imputer.fit_transform(a)
print(df)

   Marks     G     result
0   85.0     M   verygood
1   95.0     F  excellent
2   60.0  None       good
3   60.0     M    average
4   70.0     M       good
5   60.0  None   verygood
6   60.0     F   verygood
7   98.0     M  excellent

In [18]:
# Imputing missing numeric values with constant strategy
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
[85, 'M', 'verygood'],
[95, 'F', 'excellent'],
[60, None, 'good'],
[np.nan, 'M', 'average'],
[70, 'M', 'good'],
[np.nan, None, 'verygood'],
[60, 'F', 'verygood'],
[98, 'M', 'excellent']]
cols = ['Marks','G', 'R']
df = pd.DataFrame(students, columns = cols)
imputer = SimpleImputer(missing_values = np.nan, strategy = 'constant', fill_value = 80)
a = df['Marks'].values.reshape(-1,1)
df['Marks'] = imputer.fit_transform(a)
df

   Marks     G          R
0   85.0     M   verygood
1   95.0     F  excellent
2   60.0  None       good
3   80.0     M    average
4   70.0     M       good
5   80.0  None   verygood
6   60.0     F   verygood
7   98.0     M  excellent

Handling categorical values

Categorical data are variables that contain label values rather than numeric values

Nominal Variable
The variables which are having no-order those are called as Nominal Variable.

Ex: colors like blue, green and red

Ordinal Variable
The variables which are having an order those are called as ordinal Variable.

Ex: Score variables values : low, medium, high

There are 3 ways to convert categorical variables to numerical values.

Ordinal encoding

One hot encoding

Dummy variable encoding

Ordinal encoding: In ordinal encoding every nominal value is assigned an integer value for

Ex: blue : 0, green : 1, red : 2

By assigning an integer in alphabetical order to the nominal data we are trying to bring an order or trying to convert to ordinal data

Ordinal encoding is used when:Data has meaningful order like School < College < PhD

if data has no order it should not be used like Red=1, Blue=2, Green=3


Model may assume: Green (3) > Blue (2) > Red (1)

But in reality colors have no order

In [19]:
# Ordinal encoding
# asarray function
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
data = np.asarray([['blue'], ['green'], ['red']])
print(data)

[['blue']
 ['green']
 ['red']]

In [20]:
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)
print(result)

[[0.]
 [1.]
 [2.]]

One-Hot Encoding converts nominal categorical data into numerical features without introducing any ordinal relationship between the categories.

OneHotEncoder class encodes or converts categorical data into vectors.

sparse = mostly zeros

sparse=True → saves space by not storing all the zeros → output type is sparse matrix → not very redable

sparse=False → gives full array with 0s and 1s (good for learning/printing) → output type is numpy array → easy to read and understand

In [21]:
# One Hot Encoding
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
a = [['apple'], ['peer'], ['apple'], ['peer'], ['apple']]
result = np.asarray(a)
result

array([['apple'],
       ['peer'],
       ['apple'],
       ['peer'],
       ['apple']], dtype='<U5')

In [22]:
OHE = OneHotEncoder(sparse_output = False)
OHE.fit_transform(result)

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

Dummy variable encoding: Apply one hot encoding and drop the first column

array() function always makes a new copy of the data

asarray only makes a copy if needed otherwise, reuses the original if it is already an array. So, asarray is more memory efficient

In [27]:
# Dummy variable encoding
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
data = [['blue'], ['green'], ['red']]
result = np.asarray(data)
print(result)
print()
OHE = OneHotEncoder(sparse_output = False)
result = OHE.fit_transform(result)
print(result)

[['blue']
 ['green']
 ['red']]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

When we use all binary columns in one-hot encoding, one column becomes redundant or of no use because it can be derived from the others.

Ex:

o blue : 1 0 0

o green : 0 1 0

o red : 0 0 1

Dummy variable encoding example

Ex:

blue : 0 0

green : 1 0

red : 0 1

If we drop first column from the result of one hot encoding, then we will get dummy variable encoding.

In [24]:
# Dummy variable encoding
OHE = OneHotEncoder(drop = 'first', sparse_output = False)
result = OHE.fit_transform(result)
result

array([[0., 0.],
       [1., 0.],
       [0., 1.]])

Imputing Missing class values


If qunatitative replace with an average value and Median → better for skewed data and If data has outliers → use median

If qualitative (categorical data) replace it with most common value or Mode (most frequent value)

Advanced methods like KNN imputation can also be used to predict missing values based on other features.

Imputation is the process of replacing missing values with meaningful substitutes instead of removing the data.

Categorical feature may have missing values which we can impute with most frequent strategy

In [31]:
# Imputing Missing Class Values
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
students = [
[85, 'M', 'verygood'],
[95, 'F', 'excellent'],
[75, np.nan, 'good'],
[np.nan, 'M', 'average'],
[70, 'M', 'good'],
[np.nan, np.nan, 'verygood'],
[92, 'F', 'verygood'],
[98, 'M', 'excellent']]
cols = ['marks', 'gender', 'result']
df = pd.DataFrame(students, columns = cols)
print(df)
print()
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
a = df['gender'].values.reshape(-1,1)
b = df['marks'].values.reshape(-1,1)
df['marks'] = imputer.fit_transform(b)
df['gender'] = imputer.fit_transform(a).flatten()
df

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   75.0    NaN       good
3    NaN      M    average
4   70.0      M       good
5    NaN    NaN   verygood
6   92.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   75.0      M       good
3   70.0      M    average
4   70.0      M       good
5   70.0      M   verygood
6   92.0      F   verygood
7   98.0      M  excellent

But df.gender expects a 1D Series. For this we just need to flatten the 2D output using .ravel() or flatten()

.fit_transform(result) → gives shape (n, 1) → 2D

.ravel() or .flatten() → converts it back to 1D shape (n,), which can be safely assigned to df['gender'].

SimpleImputer returns a 2D array. When we manually reshape a column using reshape(-1,1), the output remains 2D, so we use flatten() to convert it back to 1D before assigning it to a DataFrame column. However, when using df[['col']], Pandas handles the conversion automatically, so flattening is not required.

imputer.fit_transform(a)

👉 Always returns 2D array

[['M'],
 ['F'],
 ['M']]

 Shape: (n, 1)

 But your column:

df['gender']

👉 expects 1D data

Pandas may automatically convert a 2D array to 1D when assigning numeric data, but this behavior is inconsistent for object data types, so explicit flattening or using DataFrame slicing is recommended.

So flatten is required in both the cases or use the syntax as df['marks'] = imputer.fit_transform(df[['marks']]) as pandas handles the shape automatically