<a href="https://colab.research.google.com/github/gmanojkumar402-max/Manoj-colab-notebooks/blob/main/Finding_Best_alogorithm_%26_Hyperparameters_using_Optuna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [54]:
import optuna
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [55]:
# loading the dataset
import numpy as np
import pandas as pd
df = pd.read_csv('/content/sample_data/titanic.csv',usecols = ['Pclass', 'Sex', 'Age', 'Fare','Survived'])
features = df.drop('Survived', axis = 'columns')
target = df['Survived']
dummies = pd.get_dummies(features['Sex'],dtype = int)
new_features = pd.concat([features,dummies],axis = 'columns')
new_features.drop(['Sex','male'], axis = 'columns', inplace = True)
new_features['Age'] = new_features['Age'].fillna(new_features.Age.mean())
X_train,X_test,y_train,y_test = train_test_split(new_features,target,test_size = 0.3, random_state = 42)

In [56]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [57]:
X_train.shape

(623, 4)

In [58]:
X_test.shape

(268, 4)

In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
# Define the objective function
def objective(trail):
  n_estimators = trail.suggest_int('n_estimators', 50, 200)
  max_depth = trail.suggest_int('max_depth',3,20)
  # creating the model
  model = RandomForestClassifier(n_estimators = n_estimators,max_depth = max_depth,random_state = 42)
  # performing cross validation
  score = cross_val_score(model,X_train,y_train,cv = 3, scoring = 'accuracy').mean()
  return score

In [60]:
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.TPESampler())
study.optimize(objective, n_trials = 50)

[I 2025-12-21 02:41:10,975] A new study created in memory with name: no-name-470f7391-2069-4a58-96f3-d8ebe4c79f29
[I 2025-12-21 02:41:11,638] Trial 0 finished with value: 0.80738263346959 and parameters: {'n_estimators': 72, 'max_depth': 5}. Best is trial 0 with value: 0.80738263346959.
[I 2025-12-21 02:41:12,588] Trial 1 finished with value: 0.7945698625046451 and parameters: {'n_estimators': 105, 'max_depth': 11}. Best is trial 0 with value: 0.80738263346959.
[I 2025-12-21 02:41:13,871] Trial 2 finished with value: 0.7993930385234732 and parameters: {'n_estimators': 110, 'max_depth': 10}. Best is trial 0 with value: 0.80738263346959.
[I 2025-12-21 02:41:16,238] Trial 3 finished with value: 0.792975040257649 and parameters: {'n_estimators': 85, 'max_depth': 11}. Best is trial 0 with value: 0.80738263346959.
[I 2025-12-21 02:41:18,207] Trial 4 finished with value: 0.8138238573021183 and parameters: {'n_estimators': 121, 'max_depth': 8}. Best is trial 4 with value: 0.8138238573021183.
[I 2025-12-21 02:41:19,359] Trial 5 finished with value: 0.7849544778892605 and parameters: {'n_estimators': 83, 'max_depth': 17}. Best is trial 4 with value: 0.8138238573021183.
[I 2025-12-21 02:41:21,246] Trial 6 finished with value: 0.7961801684627772 and parameters: {'n_estimators': 143, 'max_depth': 15}. Best is trial 4 with value: 0.8138238573021183.
[I 2025-12-21 02:41:23,913] Trial 7 finished with value: 0.8074058590362938 and parameters: {'n_estimators': 193, 'max_depth': 9}. Best is trial 4 with value: 0.8138238573021183.
[I 2025-12-21 02:41:26,269] Trial 8 finished with value: 0.8218444196705067 and parameters: {'n_estimators': 169, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:27,211] Trial 9 finished with value: 0.7785132540567323 and parameters: {'n_estimators': 69, 'max_depth': 14}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:30,430] Trial 10 finished with value: 0.8154031958379785 and parameters: {'n_estimators': 169, 'max_depth': 4}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:32,623] Trial 11 finished with value: 0.7993465873900657 and parameters: {'n_estimators': 168, 'max_depth': 3}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:34,328] Trial 12 finished with value: 0.8154264214046822 and parameters: {'n_estimators': 155, 'max_depth': 6}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:35,982] Trial 13 finished with value: 0.8202341137123746 and parameters: {'n_estimators': 143, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:37,901] Trial 14 finished with value: 0.8218444196705067 and parameters: {'n_estimators': 194, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:39,036] Trial 15 finished with value: 0.7977827325653414 and parameters: {'n_estimators': 199, 'max_depth': 13}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:40,047] Trial 16 finished with value: 0.7881596060943887 and parameters: {'n_estimators': 177, 'max_depth': 19}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:41,274] Trial 17 finished with value: 0.8218366778149387 and parameters: {'n_estimators': 184, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:41,692] Trial 18 finished with value: 0.8025594574507617 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:42,999] Trial 19 finished with value: 0.8074058590362938 and parameters: {'n_estimators': 154, 'max_depth': 9}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:44,056] Trial 20 finished with value: 0.8009491514926298 and parameters: {'n_estimators': 190, 'max_depth': 3}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:45,044] Trial 21 finished with value: 0.8218366778149387 and parameters: {'n_estimators': 181, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:46,069] Trial 22 finished with value: 0.8218366778149387 and parameters: {'n_estimators': 183, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:47,192] Trial 23 finished with value: 0.809008423138858 and parameters: {'n_estimators': 200, 'max_depth': 9}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:48,077] Trial 24 finished with value: 0.8137928898798464 and parameters: {'n_estimators': 165, 'max_depth': 5}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:48,855] Trial 25 finished with value: 0.8218444196705067 and parameters: {'n_estimators': 140, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:49,618] Trial 26 finished with value: 0.792975040257649 and parameters: {'n_estimators': 130, 'max_depth': 12}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:50,493] Trial 27 finished with value: 0.7977904744209092 and parameters: {'n_estimators': 153, 'max_depth': 10}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:51,219] Trial 28 finished with value: 0.80738263346959 and parameters: {'n_estimators': 135, 'max_depth': 6}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:52,088] Trial 29 finished with value: 0.8121825839217144 and parameters: {'n_estimators': 163, 'max_depth': 4}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:52,780] Trial 30 finished with value: 0.8138238573021183 and parameters: {'n_estimators': 119, 'max_depth': 8}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:53,972] Trial 31 finished with value: 0.8170289855072465 and parameters: {'n_estimators': 178, 'max_depth': 6}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:55,547] Trial 32 finished with value: 0.812221293199554 and parameters: {'n_estimators': 187, 'max_depth': 8}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:56,648] Trial 33 finished with value: 0.7961956521739131 and parameters: {'n_estimators': 173, 'max_depth': 10}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:57,215] Trial 34 finished with value: 0.8121980676328503 and parameters: {'n_estimators': 102, 'max_depth': 6}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:58,027] Trial 35 finished with value: 0.792975040257649 and parameters: {'n_estimators': 141, 'max_depth': 12}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:58,951] Trial 36 finished with value: 0.7977827325653414 and parameters: {'n_estimators': 158, 'max_depth': 11}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:41:59,943] Trial 37 finished with value: 0.8137928898798464 and parameters: {'n_estimators': 191, 'max_depth': 4}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:00,763] Trial 38 finished with value: 0.8138315991576861 and parameters: {'n_estimators': 147, 'max_depth': 8}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:01,365] Trial 39 finished with value: 0.8202263718568067 and parameters: {'n_estimators': 106, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:02,369] Trial 40 finished with value: 0.7961956521739131 and parameters: {'n_estimators': 173, 'max_depth': 10}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:03,359] Trial 41 finished with value: 0.8202341137123746 and parameters: {'n_estimators': 179, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:04,343] Trial 42 finished with value: 0.8137928898798464 and parameters: {'n_estimators': 186, 'max_depth': 5}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:05,444] Trial 43 finished with value: 0.812221293199554 and parameters: {'n_estimators': 199, 'max_depth': 8}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:06,596] Trial 44 finished with value: 0.8042007308311656 and parameters: {'n_estimators': 162, 'max_depth': 9}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:08,104] Trial 45 finished with value: 0.8218366778149387 and parameters: {'n_estimators': 184, 'max_depth': 7}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:09,364] Trial 46 finished with value: 0.7945698625046451 and parameters: {'n_estimators': 193, 'max_depth': 16}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:10,274] Trial 47 finished with value: 0.8121980676328503 and parameters: {'n_estimators': 171, 'max_depth': 6}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:11,221] Trial 48 finished with value: 0.8137928898798464 and parameters: {'n_estimators': 179, 'max_depth': 4}. Best is trial 8 with value: 0.8218444196705067.
[I 2025-12-21 02:42:11,937] Trial 49 finished with value: 0.8138238573021183 and parameters: {'n_estimators': 123, 'max_depth': 8}. Best is trial 8 with value: 0.8218444196705067.

In [61]:
study.best_trial.value

0.8218444196705067

In [62]:
study.best_trial.params

{'n_estimators': 169, 'max_depth': 7}

In [63]:
from sklearn.metrics import accuracy_score
best_model = RandomForestClassifier(**study.best_trial.params,random_state = 42)
best_model.fit(X_train,y_train)
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.8171641791044776

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
# Define the objective function
def objective(trail):
  n_estimators = trail.suggest_int('n_estimators', 50, 200)
  max_depth = trail.suggest_int('max_depth',3,20)
  # creating the model
  model = RandomForestClassifier(n_estimators = n_estimators,max_depth = max_depth,random_state = 42)
  # performing cross validation
  score = cross_val_score(model,X_train,y_train,cv = 3, scoring = 'accuracy').mean()
  return score

In [65]:
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.RandomSampler())
study.optimize(objective, n_trials = 50)

[I 2025-12-21 02:42:12,422] A new study created in memory with name: no-name-24b1d38a-7b01-4138-a716-4af3fe876327
[I 2025-12-21 02:42:13,200] Trial 0 finished with value: 0.792975040257649 and parameters: {'n_estimators': 85, 'max_depth': 11}. Best is trial 0 with value: 0.792975040257649.
[I 2025-12-21 02:42:14,839] Trial 1 finished with value: 0.7865493001362567 and parameters: {'n_estimators': 109, 'max_depth': 17}. Best is trial 0 with value: 0.792975040257649.
[I 2025-12-21 02:42:16,830] Trial 2 finished with value: 0.792975040257649 and parameters: {'n_estimators': 146, 'max_depth': 17}. Best is trial 0 with value: 0.792975040257649.
[I 2025-12-21 02:42:18,282] Trial 3 finished with value: 0.8025517155951939 and parameters: {'n_estimators': 144, 'max_depth': 3}. Best is trial 3 with value: 0.8025517155951939.
[I 2025-12-21 02:42:22,394] Trial 4 finished with value: 0.8170289855072465 and parameters: {'n_estimators': 199, 'max_depth': 6}. Best is trial 4 with value: 0.8170289855072465.
[I 2025-12-21 02:42:24,988] Trial 5 finished with value: 0.7897621701969527 and parameters: {'n_estimators': 158, 'max_depth': 19}. Best is trial 4 with value: 0.8170289855072465.
[I 2025-12-21 02:42:27,296] Trial 6 finished with value: 0.792975040257649 and parameters: {'n_estimators': 169, 'max_depth': 16}. Best is trial 4 with value: 0.8170289855072465.
[I 2025-12-21 02:42:28,827] Trial 7 finished with value: 0.789746686485817 and parameters: {'n_estimators': 120, 'max_depth': 16}. Best is trial 4 with value: 0.8170289855072465.
[I 2025-12-21 02:42:31,138] Trial 8 finished with value: 0.8137928898798464 and parameters: {'n_estimators': 194, 'max_depth': 4}. Best is trial 4 with value: 0.8170289855072465.
[I 2025-12-21 02:42:34,580] Trial 9 finished with value: 0.7929672984020811 and parameters: {'n_estimators': 154, 'max_depth': 18}. Best is trial 4 with value: 0.8170289855072465.
[I 2025-12-21 02:42:37,906] Trial 10 finished with value: 0.8218444196705067 and parameters: {'n_estimators': 200, 'max_depth': 7}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:38,581] Trial 11 finished with value: 0.8170212436516785 and parameters: {'n_estimators': 83, 'max_depth': 7}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:38,961] Trial 12 finished with value: 0.80738263346959 and parameters: {'n_estimators': 70, 'max_depth': 5}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:39,953] Trial 13 finished with value: 0.7977904744209092 and parameters: {'n_estimators': 174, 'max_depth': 13}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:40,892] Trial 14 finished with value: 0.7913647342995169 and parameters: {'n_estimators': 162, 'max_depth': 20}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:41,368] Trial 15 finished with value: 0.8122135513439862 and parameters: {'n_estimators': 82, 'max_depth': 8}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:42,374] Trial 16 finished with value: 0.8106187290969901 and parameters: {'n_estimators': 180, 'max_depth': 8}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:42,658] Trial 17 finished with value: 0.8025594574507617 and parameters: {'n_estimators': 54, 'max_depth': 3}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:43,586] Trial 18 finished with value: 0.7913647342995169 and parameters: {'n_estimators': 160, 'max_depth': 19}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:44,452] Trial 19 finished with value: 0.7977827325653414 and parameters: {'n_estimators': 153, 'max_depth': 11}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:44,953] Trial 20 finished with value: 0.7833441719311285 and parameters: {'n_estimators': 86, 'max_depth': 17}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:45,775] Trial 21 finished with value: 0.7945776043602132 and parameters: {'n_estimators': 140, 'max_depth': 14}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:46,555] Trial 22 finished with value: 0.8025671993063298 and parameters: {'n_estimators': 99, 'max_depth': 3}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:47,625] Trial 23 finished with value: 0.789746686485817 and parameters: {'n_estimators': 124, 'max_depth': 17}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:48,612] Trial 24 finished with value: 0.7897699120525208 and parameters: {'n_estimators': 124, 'max_depth': 14}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:49,126] Trial 25 finished with value: 0.8009568933481978 and parameters: {'n_estimators': 102, 'max_depth': 3}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:49,515] Trial 26 finished with value: 0.7817338659729964 and parameters: {'n_estimators': 66, 'max_depth': 15}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:50,263] Trial 27 finished with value: 0.7897544283413849 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:51,318] Trial 28 finished with value: 0.8218444196705067 and parameters: {'n_estimators': 195, 'max_depth': 7}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:52,390] Trial 29 finished with value: 0.7929595565465131 and parameters: {'n_estimators': 187, 'max_depth': 18}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:53,103] Trial 30 finished with value: 0.7897544283413849 and parameters: {'n_estimators': 125, 'max_depth': 16}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:53,536] Trial 31 finished with value: 0.7801235600148644 and parameters: {'n_estimators': 73, 'max_depth': 16}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:54,272] Trial 32 finished with value: 0.7913724761550848 and parameters: {'n_estimators': 128, 'max_depth': 12}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:55,253] Trial 33 finished with value: 0.8106187290969901 and parameters: {'n_estimators': 175, 'max_depth': 8}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:55,628] Trial 34 finished with value: 0.8138161154465502 and parameters: {'n_estimators': 62, 'max_depth': 7}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:56,055] Trial 35 finished with value: 0.7865725257029604 and parameters: {'n_estimators': 70, 'max_depth': 13}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:56,866] Trial 36 finished with value: 0.8202418555679425 and parameters: {'n_estimators': 147, 'max_depth': 7}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:57,418] Trial 37 finished with value: 0.7961724266072093 and parameters: {'n_estimators': 97, 'max_depth': 11}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:58,182] Trial 38 finished with value: 0.7897544283413849 and parameters: {'n_estimators': 134, 'max_depth': 18}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:42:59,707] Trial 39 finished with value: 0.7945776043602132 and parameters: {'n_estimators': 186, 'max_depth': 14}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:01,018] Trial 40 finished with value: 0.7977904744209092 and parameters: {'n_estimators': 147, 'max_depth': 13}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:01,804] Trial 41 finished with value: 0.7897544283413849 and parameters: {'n_estimators': 134, 'max_depth': 19}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:02,120] Trial 42 finished with value: 0.8186238077542426 and parameters: {'n_estimators': 52, 'max_depth': 7}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:02,900] Trial 43 finished with value: 0.8025517155951939 and parameters: {'n_estimators': 156, 'max_depth': 3}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:03,305] Trial 44 finished with value: 0.7785209959123002 and parameters: {'n_estimators': 68, 'max_depth': 14}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:03,804] Trial 45 finished with value: 0.7881673479499566 and parameters: {'n_estimators': 82, 'max_depth': 15}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:04,781] Trial 46 finished with value: 0.8106187290969901 and parameters: {'n_estimators': 176, 'max_depth': 8}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:05,389] Trial 47 finished with value: 0.7865570419918247 and parameters: {'n_estimators': 103, 'max_depth': 19}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:06,416] Trial 48 finished with value: 0.7881518642388207 and parameters: {'n_estimators': 179, 'max_depth': 19}. Best is trial 10 with value: 0.8218444196705067.
[I 2025-12-21 02:43:06,943] Trial 49 finished with value: 0.7849544778892605 and parameters: {'n_estimators': 91, 'max_depth': 19}. Best is trial 10 with value: 0.8218444196705067.

In [66]:
study.best_trial.value

0.8218444196705067

In [67]:
study.best_trial.params

{'n_estimators': 200, 'max_depth': 7}

In [68]:
search_space = {'n_estimators':[50, 100, 150,200],'max_depth':[5,10,15,20]}

In [69]:
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-12-21 02:43:06,973] A new study created in memory with name: no-name-6c80933a-ed3b-468b-8777-25c61e4083e2
[I 2025-12-21 02:43:07,523] Trial 0 finished with value: 0.804162021553326 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.804162021553326.
[I 2025-12-21 02:43:08,385] Trial 1 finished with value: 0.796187910318345 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.804162021553326.
[I 2025-12-21 02:43:08,680] Trial 2 finished with value: 0.7801313018704322 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 0 with value: 0.804162021553326.
[I 2025-12-21 02:43:09,257] Trial 3 finished with value: 0.7897621701969527 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 0 with value: 0.804162021553326.
[I 2025-12-21 02:43:09,851] Trial 4 finished with value: 0.7849467360336927 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 0 with value: 0.804162021553326.
[I 2025-12-21 02:43:10,146] Trial 5 finished with value: 0.7961801684627772 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 0 with value: 0.804162021553326.
[I 2025-12-21 02:43:10,951] Trial 6 finished with value: 0.808985197572154 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 6 with value: 0.808985197572154.
[I 2025-12-21 02:43:12,269] Trial 7 finished with value: 0.7913647342995169 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 6 with value: 0.808985197572154.
[I 2025-12-21 02:43:13,573] Trial 8 finished with value: 0.7945698625046451 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 6 with value: 0.808985197572154.
[I 2025-12-21 02:43:14,706] Trial 9 finished with value: 0.7993930385234734 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 6 with value: 0.808985197572154.
[I 2025-12-21 02:43:15,830] Trial 10 finished with value: 0.7897544283413849 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 6 with value: 0.808985197572154.
[I 2025-12-21 02:43:16,979] Trial 11 finished with value: 0.7945698625046451 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 6 with value: 0.808985197572154.
[I 2025-12-21 02:43:18,017] Trial 12 finished with value: 0.8170057599405425 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 12 with value: 0.8170057599405425.
[I 2025-12-21 02:43:18,298] Trial 13 finished with value: 0.8025594574507617 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 12 with value: 0.8170057599405425.
[I 2025-12-21 02:43:18,892] Trial 14 finished with value: 0.8026059085841695 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 12 with value: 0.8170057599405425.
[I 2025-12-21 02:43:19,190] Trial 15 finished with value: 0.7785364796234361 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 12 with value: 0.8170057599405425.

In [70]:
study.best_trial.value

0.8170057599405425

In [71]:
study.best_trial.params

{'n_estimators': 200, 'max_depth': 5}

Optuna Visualization

In [80]:
# for visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate,plot_slice,plot_param_importances,plot_contour

In [81]:
# 1 optimization history
plot_optimization_history(study).show()

In [82]:
#2 parallel coordinates plot
plot_parallel_coordinate(study).show()

In [83]:
#3 Slice Plot
plot_slice(study).show()

In [84]:
# 4. Hyperparameter Importance
plot_param_importances(study).show()

In [85]:
# 5. contour plot
plot_contour(study).show()

Optimizing multiple ML models

In [91]:
# importing the required Libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [96]:
# lets Define objectyve function for optuna
def objective(trial):
  # choosing the algorithms to tune
  algorithm_name = trial.suggest_categorical('algorithm', ['RandomForest', 'GradientBoosting', 'SVM'])

  if algorithm_name == 'RandomForest':
    n_estimators = trial.suggest_int('n_estimators', 50,300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])
    model = RandomForestClassifier(n_estimators = n_estimators, max_depth = max_depth,min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42)
  elif algorithm_name == 'GradientBoosting':
    # Gradient Boosting hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

    model = GradientBoostingClassifier(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )
  elif algorithm_name == 'SVM':
    # SVM hyperparameters
    c = trial.suggest_float('C', 0.1, 100, log=True)
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

    model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

 # Perform cross-validation and return the mean accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  return score

In [97]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-12-21 03:06:52,530] A new study created in memory with name: no-name-b8c6eef6-159b-4721-9bda-952934bd638b
[I 2025-12-21 03:06:52,563] Trial 0 finished with value: 0.7849544778892605 and parameters: {'algorithm': 'SVM', 'C': 0.38594898267248434, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 0 with value: 0.7849544778892605.
[I 2025-12-21 03:06:52,634] Trial 1 finished with value: 0.7849080267558528 and parameters: {'algorithm': 'SVM', 'C': 15.090327697935384, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.7849544778892605.
[I 2025-12-21 03:06:53,601] Trial 2 finished with value: 0.8025517155951939 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 253, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.8025517155951939.
[I 2025-12-21 03:06:54,580] Trial 3 finished with value: 0.8009414096370618 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 252, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.8025517155951939.
[I 2025-12-21 03:06:55,861] Trial 4 finished with value: 0.8041852471200297 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 243, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 4 with value: 0.8041852471200297.
[I 2025-12-21 03:06:55,897] Trial 5 finished with value: 0.7945234113712374 and parameters: {'algorithm': 'SVM', 'C': 2.391398908545155, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.8041852471200297.
[I 2025-12-21 03:06:56,727] Trial 6 finished with value: 0.8025826830174657 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 198, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 4 with value: 0.8041852471200297.
[I 2025-12-21 03:06:57,485] Trial 7 finished with value: 0.8250418060200669 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 82, 'learning_rate': 0.018435437556116117, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 7 with value: 0.8250418060200669.
[I 2025-12-21 03:06:59,528] Trial 8 finished with value: 0.7672953053387835 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 136, 'learning_rate': 0.12208266613659341, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.8250418060200669.
[I 2025-12-21 03:07:01,685] Trial 9 finished with value: 0.8058032949337298 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 295, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 7 with value: 0.8250418060200669.
[I 2025-12-21 03:07:02,410] Trial 10 finished with value: 0.8169980180849746 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 52, 'learning_rate': 0.011747938585151958, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.8250418060200669.
[I 2025-12-21 03:07:02,944] Trial 11 finished with value: 0.8153877121268426 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 54, 'learning_rate': 0.010280815071084925, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.8250418060200669.
[I 2025-12-21 03:07:03,437] Trial 12 finished with value: 0.8282469342251951 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 53, 'learning_rate': 0.013153493450737914, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:04,583] Trial 13 finished with value: 0.7881518642388207 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 113, 'learning_rate': 0.030182545350593844, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:05,427] Trial 14 finished with value: 0.8202341137123746 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 99, 'learning_rate': 0.03023007382229065, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:06,343] Trial 15 finished with value: 0.8138161154465502 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 90, 'learning_rate': 0.021834261613176146, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:07,963] Trial 16 finished with value: 0.7785674470457079 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 156, 'learning_rate': 0.07857810124328371, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:08,929] Trial 17 finished with value: 0.7801545274371362 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 78, 'learning_rate': 0.22245136836057466, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:10,642] Trial 18 finished with value: 0.7833441719311285 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 183, 'learning_rate': 0.018424679345821385, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:11,764] Trial 19 finished with value: 0.7849467360336925 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 126, 'learning_rate': 0.04678479590409773, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:11,804] Trial 20 finished with value: 0.6597377059333581 and parameters: {'algorithm': 'SVM', 'C': 69.84186922622627, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:12,562] Trial 21 finished with value: 0.8170289855072465 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 87, 'learning_rate': 0.027735700639081762, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:13,690] Trial 22 finished with value: 0.826644370122631 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 96, 'learning_rate': 0.016527536568179402, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:14,315] Trial 23 finished with value: 0.8234237582063669 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 71, 'learning_rate': 0.015216132482414537, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:14,960] Trial 24 finished with value: 0.8090239068499939 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 50, 'learning_rate': 0.015688043339225476, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:16,125] Trial 25 finished with value: 0.7929905239687849 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 117, 'learning_rate': 0.04598108042238255, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:17,531] Trial 26 finished with value: 0.8250418060200669 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 151, 'learning_rate': 0.01013137866965203, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:18,026] Trial 27 finished with value: 0.8234237582063669 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 72, 'learning_rate': 0.02175223014279567, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:18,943] Trial 28 finished with value: 0.8250418060200669 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 104, 'learning_rate': 0.015262888873886143, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:18,990] Trial 29 finished with value: 0.7656772575250836 and parameters: {'algorithm': 'SVM', 'C': 0.12220170799162224, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:19,020] Trial 30 finished with value: 0.7849544778892605 and parameters: {'algorithm': 'SVM', 'C': 2.0649835474967184, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:20,376] Trial 31 finished with value: 0.8218366778149386 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 147, 'learning_rate': 0.011847458718601704, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:21,911] Trial 32 finished with value: 0.8154186795491144 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 156, 'learning_rate': 0.011661833228813777, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:23,742] Trial 33 finished with value: 0.8026059085841695 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 206, 'learning_rate': 0.015977587064075868, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:24,346] Trial 34 finished with value: 0.8282469342251951 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 65, 'learning_rate': 0.010309539267052054, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:24,742] Trial 35 finished with value: 0.8057878112225939 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 67, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:24,800] Trial 36 finished with value: 0.8009414096370618 and parameters: {'algorithm': 'SVM', 'C': 56.57815401029192, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:26,656] Trial 37 finished with value: 0.7994085222346091 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 96, 'learning_rate': 0.0229505925447269, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:27,179] Trial 38 finished with value: 0.7817338659729964 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 67, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:27,736] Trial 39 finished with value: 0.8170135017961105 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 84, 'learning_rate': 0.034692303959944784, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:28,124] Trial 40 finished with value: 0.8041929889755978 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 63, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:29,089] Trial 41 finished with value: 0.8250418060200668 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 106, 'learning_rate': 0.010279305545132423, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:31,025] Trial 42 finished with value: 0.7961724266072093 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 217, 'learning_rate': 0.013981108171534567, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:32,137] Trial 43 finished with value: 0.8218366778149387 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 125, 'learning_rate': 0.019885029183534672, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:33,910] Trial 44 finished with value: 0.8089929394277221 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 169, 'learning_rate': 0.01212260376265215, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:34,708] Trial 45 finished with value: 0.8282469342251951 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 87, 'learning_rate': 0.010000987188549465, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:35,413] Trial 46 finished with value: 0.794577604360213 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 79, 'learning_rate': 0.08085079797031423, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:35,977] Trial 47 finished with value: 0.826652111978199 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 59, 'learning_rate': 0.013980219923343046, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:36,055] Trial 48 finished with value: 0.7849080267558528 and parameters: {'algorithm': 'SVM', 'C': 11.371809326674164, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:36,586] Trial 49 finished with value: 0.8250495478756349 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 59, 'learning_rate': 0.013402525045580253, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:36,887] Trial 50 finished with value: 0.8089929394277221 and parameters: {'algorithm': 'RandomForest', 'n_estimators': 53, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:37,455] Trial 51 finished with value: 0.826652111978199 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 62, 'learning_rate': 0.01271720828328655, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:40,773] Trial 52 finished with value: 0.7977982162764771 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 286, 'learning_rate': 0.013869620255821242, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:41,585] Trial 53 finished with value: 0.826644370122631 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 94, 'learning_rate': 0.018491386687403237, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:42,223] Trial 54 finished with value: 0.826644370122631 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 77, 'learning_rate': 0.012301323614472753, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:42,729] Trial 55 finished with value: 0.8250418060200668 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 62, 'learning_rate': 0.01702515406416107, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:43,488] Trial 56 finished with value: 0.8282469342251951 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 87, 'learning_rate': 0.010397226874962372, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:44,261] Trial 57 finished with value: 0.826652111978199 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 81, 'learning_rate': 0.010036917754214, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:44,761] Trial 58 finished with value: 0.8137928898798464 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 50, 'learning_rate': 0.012093073164677167, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:45,409] Trial 59 finished with value: 0.7881596060943887 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 63, 'learning_rate': 0.29001364845079436, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:46,235] Trial 60 finished with value: 0.8282469342251951 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 90, 'learning_rate': 0.010163743048279874, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:47,218] Trial 61 finished with value: 0.8250418060200668 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 107, 'learning_rate': 0.01005733117768795, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:48,005] Trial 62 finished with value: 0.8202186300012387 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 89, 'learning_rate': 0.012893791604097291, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:48,687] Trial 63 finished with value: 0.8282469342251951 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 73, 'learning_rate': 0.011538714088412264, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:49,313] Trial 64 finished with value: 0.8202186300012387 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 73, 'learning_rate': 0.011089629133147637, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:50,392] Trial 65 finished with value: 0.8234392419175028 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 116, 'learning_rate': 0.014565230696205468, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:51,704] Trial 66 finished with value: 0.7833673974978322 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 88, 'learning_rate': 0.1490370477204545, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:51,764] Trial 67 finished with value: 0.7865183327139849 and parameters: {'algorithm': 'SVM', 'C': 0.5681259693368017, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 12 with value: 0.8282469342251951.
[I 2025-12-21 03:07:52,777] Trial 68 finished with value: 0.8202186300012387 and parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 77, 'learning_rate': 0.011178827944950617, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.8282469342251951.

In [98]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'algorithm': 'GradientBoosting', 'n_estimators': 57, 'learning_rate': 0.010034906621422514, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 9}
Best trial accuracy: 0.8298494983277592

In [99]:
# Total trials information in a dataframe
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_algorithm,params_bootstrap,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.784954,2025-12-21 03:06:52.532981,2025-12-21 03:06:52.563616,0 days 00:00:00.030635,0.385949,SVM,NaN,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.784908,2025-12-21 03:06:52.564730,2025-12-21 03:06:52.634280,0 days 00:00:00.069550,15.090328,SVM,NaN,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.802552,2025-12-21 03:06:52.635367,2025-12-21 03:06:53.601639,0 days 00:00:00.966272,NaN,RandomForest,False,NaN,NaN,NaN,3.0,1.0,9.0,253.0,COMPLETE
3,3,0.800941,2025-12-21 03:06:53.603113,2025-12-21 03:06:54.580033,0 days 00:00:00.976920,NaN,RandomForest,False,NaN,NaN,NaN,4.0,5.0,9.0,252.0,COMPLETE
4,4,0.804185,2025-12-21 03:06:54.581199,2025-12-21 03:06:55.861722,0 days 00:00:01.280523,NaN,RandomForest,True,NaN,NaN,NaN,11.0,7.0,2.0,243.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.828247,2025-12-21 03:08:13.678593,2025-12-21 03:08:14.311838,0 days 00:00:00.633245,NaN,GradientBoosting,NaN,NaN,NaN,0.012463,19.0,9.0,8.0,68.0,COMPLETE
96,96,0.825042,2025-12-21 03:08:14.312840,2025-12-21 03:08:15.013280,0 days 00:00:00.700440,NaN,GradientBoosting,NaN,NaN,NaN,0.014392,13.0,9.0,3.0,76.0,COMPLETE
97,97,0.796157,2025-12-21 03:08:15.014319,2025-12-21 03:08:17.561314,0 days 00:00:02.546995,NaN,GradientBoosting,NaN,NaN,NaN,0.016495,15.0,8.0,4.0,192.0,COMPLETE
98,98,0.784954,2025-12-21 03:08:17.562393,2025-12-21 03:08:17.604312,0 days 00:00:00.041919,0.116715,SVM,NaN,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.816998,2025-12-21 03:08:17.605131,2025-12-21 03:08:18.311906,0 days 00:00:00.706775,NaN,GradientBoosting,NaN,NaN,NaN,0.010876,19.0,10.0,10.0,56.0,COMPLETE

In [104]:
study.trials_dataframe()['params_algorithm'].value_counts()

params_algorithm
GradientBoosting    78
SVM                 11
RandomForest        11
Name: count, dtype: int64

In [105]:
# average accuracy of each algorithm
study.trials_dataframe().groupby('params_algorithm')['value'].mean()

params_algorithm
GradientBoosting    0.814699
RandomForest        0.801848
SVM                 0.763329
Name: value, dtype: float64