<a href="https://colab.research.google.com/github/gmanojkumar402-max/Manoj-colab-notebooks/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Series and DataFrames deal with array data and tabular data respectively


The Pandas Series is a one-dimensional labeled array

# Creating an empty series

In [ ]:
import pandas as pd
s = pd.Series()
print(s)

Series([], dtype: object)

Seies is a predefined class in pandas

In [ ]:
from pandas import Series
s = Series()
print(s,type(s))

Series([], dtype: object) <class 'pandas.core.series.Series'>

In the back end during object creation by default constructor will get executed for every predefined class.

In [ ]:
a = [1,2,3,4,5,6,6,6, 'm']
s = Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    6
7    6
8    m
dtype: object

If heterogenous data is available series by default will call object data type

in panadas index will be displayed by default to all the data structure.

In series data structure by default it will display the data type.

In [ ]:
# providing name to the Series
a = [1,2,3,4,5]
s = pd.Series(a,name = 'first')
print(s,type(s))

0    1
1    2
2    3
3    4
4    5
Name: first, dtype: int64 <class 'pandas.core.series.Series'>

a = positional argu and name="first" is keyword arg

name is a predefined variable in pandas

In [ ]:
# naming the predefined variable wrong throws an error
a = [1,2,3,4,5]
s = Series(a, namee = 'first')
print(s)

TypeError: Series.__init__() got an unexpected keyword argument 'namee'

In python string is represented as str and in pandas as object

In [ ]:
from pandas import Series
a = ['m', 'k', 'lp']
s= Series(a)
print(s)

0     m
1     k
2    lp
dtype: object

Note: In python input is  a predefined function and its return type is always string

In [ ]:
r = range(10)
l = list(r)
print(l)
s = Series(l)
print(s)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
r = range(1,100)
a = list(r)
print(a)
s = Series(a)
print(s)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

The generic name for an index is an axis. and index is also called as label

Based on requirement we can even customize index and these are called as axis labels

In [ ]:
a = [1,2,3,4,5]
i = [10,20,30,40,50]
s = Series(a, index = i, name = 'manoj')
# a = positional arg, index = i --> keyword arg,
# name = 'manoj' --> keyword arg
print(s)

10    1
20    2
30    3
40    4
50    5
Name: manoj, dtype: int64

Length of values (5) does not match length of index (3)

In [ ]:
a = [1,2,3,4,5]
i = [10,20,30,40]
s = Series(a, index = i)
print(s)

ValueError: Length of values (5) does not match length of index (4)

To see all the predefined variable (args) in Series we have a function called  help()

Duplicate index is possible in pandas and we can even provide string as index

In [ ]:
a = [1,2,3,4,5]
i = [10,10,20,30,'m']
s = Series(a, index = i)
print(s)

10    1
10    2
20    3
30    4
m     5
dtype: int64

In [ ]:
prices = [1,2,3,4,5]
product = ['a','b','c','d','e']
s = Series(prices, index = product, name = 'phones')
print(s)

a    1
b    2
c    3
d    4
e    5
Name: phones, dtype: int64

Accessing series values using index

In [ ]:
a = [1,2,3,4,5]
s = pd. Series(a)
print(s[0])
print(s[1])

1
2

In [ ]:
price = [5000, 10000,100000]
product = ['nokia', 'samsung', 'iphone']
s = Series(price, index = product, name = 'phone')
print(s['nokia'])

5000

NaN Value


NAN is to represent the missing values in data


The data type of NaN is float and these NAN values need to be handled by us

We can store empty value in python by using None data type

In [ ]:
a = [1,2,3,None]
s = Series(a)
print(a)
print(s)

[1, 2, 3, None]
0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In any given data if at least one Nan is available then it will reflect in the whole data type

values attribute return group of values as an array

In python calss we will have methods and in Series calss we will have methods and attributes

In [ ]:
# Series attributes
class Manoj:
  def __init__(self):
    self.age = 16
  def display(self):
    print('fcuk')
m = Manoj()
print(m.age)
m.display()
# to access a variable parenthesis is not reuired
# In case of method it is required
# attribute variable returns the information
# method performs an operation

16
fcuk

in a given series to access all the values at once then we have an attribute called values.

In [ ]:
# values
a = [1,2,3,4,5]
s = Series(a)
print(s.values)
# we can see below the return type is array

[1 2 3 4 5]

In [ ]:
# index
a = [1,2,3,4,5]
s = Series(a)
print(s.index)

RangeIndex(start=0, stop=5, step=1)

In [ ]:
a = [1,2,3,4,5]
i = ['a','b','c','d','e']
s = Series(a, index = i)
print(s)
print(s.index)

a    1
b    2
c    3
d    4
e    5
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

customized index will return all values in the output

In [ ]:
from pandas import Series
dir(Series())

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [ ]:
# dtypes
a = [1,2,3,4,5]
s = Series(a)
print(s.dtype)

int64

In [ ]:
# size
a =[1,2,3,4,5]
s = Series(a)
print(s.size)

5

In [ ]:
# len function can be applied on series
a = [1,2,3,4,5]
s = Series(a)
print(len(s))

5

In [ ]:
# Series Methods
a = [1,2,3,4,5,6,7]
s = Series(a)
print(s)
print(s.head())

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# To access top 3 values
a = [1,2,3,4,5,6,7]
s = Series(a)
print(s)
print(s.head(3))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
0    1
1    2
2    3
dtype: int64

In [ ]:
# tail
a = [1,2,3,4,5]
s = Series(a)
print(s.tail(2))

3    4
4    5
dtype: int64

In [ ]:
# Name error
a = [10,20,30,40]
S = series(a)
print(S)

NameError: name 'series' is not defined

In [ ]:
# sum
a = [1,2,3,4,5]
s = Series(a)
print(s.sum())

15

To explicitly create NaN below is the syntax

series allows duplicate values

In [ ]:
import numpy as np
a = [1,2,3,4,5,6,6,np.nan]
s = Series(a)
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    NaN
dtype: float64

In [ ]:
# mean method
a = [1,2,3,4,5,6]
s = Series(a)
print(s.mean())

3.5

In [ ]:
# describe method
import pandas as pd
a = [1,2,3,4,5]
s = pd.Series(a)
print(s.describe())

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [ ]:
# unique method
import pandas as pd
a = [1,2,3,4,4,4,4,5,1,2,3]
s = Series(a)
print(s.unique())

[1 2 3 4 5]

In [ ]:
# nunique [gives the count of total unique values]
a = [1,2,3,4,4,4,4,5,6]
s = Series(a)
print(s.nunique())

6

DataFrame can be created using single list, nested list, dict, using another DataFrame and Loading files

In [ ]:
from pandas import DataFrame
# Empty data frame
df = DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
# DataFrame using a list
# with single list we will get single column DataFrame
a = [1,2,3,4,5]
df = DataFrame(a)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
# Single column dataframe and checking the length
import pandas as pd
a = [1,2,3,4,5]
df = DataFrame(a)
print(df)
print()
print(len(df))

   0
0  1
1  2
2  3
3  4
4  5

5

In [ ]:
# DataFrame using list of lists ot nested list
a = [[1,2,3],['mk','gpn','p'],[5000,6000,7000]]
df = pd.DataFrame(a)
print(df)

      0     1     2
0     1     2     3
1    mk   gpn     p
2  5000  6000  7000

In [ ]:
# Customizing the DataFrame column names
a = [[1,2,3],['mk','gpn','p'],[5000,6000,7000]]
col = ['age', 'name','salary']
df = pd.DataFrame(a, columns = col)
print(df)

    age  name salary
0     1     2      3
1    mk   gpn      p
2  5000  6000   7000

In [ ]:
class Manoj:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def display(self):
    print(self.name,self.age)
m = Manoj('lkg','ukg')
m.display()

lkg ukg

In [ ]:
class Manoj:
  def __init__(self,name,age):
    self.name = name
    self.age = age
    print(self.name,self.age)
m = Manoj('lkg','ukg')

lkg ukg

In [ ]:
# DataFrame using dict
a = {'Name':['manoj'],'age':[26],'salary':[6000]}
df = pd.DataFrame(a)
print(df)

    Name  age  salary
0  manoj   26    6000

In [ ]:
a = {'name':['manoj','kkg','pkg'],'age':[23,24,25], 'salary':[2000,3000,4000]}
df = DataFrame(a)
print(df)

    name  age  salary
0  manoj   23    2000
1    kkg   24    3000
2    pkg   25    4000

In [ ]:
a = {'name':['manoj','kkg','pkg'],'age':[23,24,25], 'salary':[2000,3000,4000]}
i = [1,2,3]
df = DataFrame(a, index = i )
print(df)

    name  age  salary
1  manoj   23    2000
2    kkg   24    3000
3    pkg   25    4000

function calling is assigned to a variable when there is a return statment

In [47]:
# creating DataFrame using csv file
import pandas as pd
df = pd.read_csv('/content/sample_data/sales1.csv')
print(df)

     Order ID Customer Name                 Product  Quantity
0      166837         Veeru  34in Ultrawide Monitor         2
1      166838         Tarun             Samsung m10         3
2      166839         Kedar            20in Monitor         1
3      166840       Lavanya               iPhone 11         3
4      166841          Venu      Macbook Pro Laptop         2
..        ...           ...                     ...       ...
595    167403        Balaji      Macbook Pro Laptop         1
596    167404       Lavanya         ThinkPad Laptop         1
597    167405          Venu           Flatscreen TV         1
598    167406        Siddhu             Samsung m20         2
599    167407         Tarun      LG Washing Machine         1

[600 rows x 4 columns]

json file contains data in  key-value pairs and arrays.


json files are mainly used to transfer data from one location to another

To load excel file we need  to install on library -->
pip install xlrd

reading data from a web page

In [51]:
url = "https://en.wikipedia.org/wiki/List_of_automotive_manufacturers_by_production"
df = pd.read_html(url)
print(df[1])

HTTPError: HTTP Error 403: Forbidden

In [52]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_automotive_manufacturers_by_production"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

df = pd.read_html(response.text)

print(df[1])

   Rank in 2024  ... Sold vehicles (2021)
0             1  ...            9562483.0
1             2  ...            8882346.0
2             3  ...            6668037.0
3             4  ...            6294385.0
4             5  ...            6142200.0
5             6  ...            3942755.0
6             7  ...                  NaN
7             8  ...            4456728.0
8             9  ...            4064999.0
9            10  ...                  NaN
10           11  ...            2314547.0
11           12  ...            2521596.0
12           13  ...            2330169.0
13           14  ...            2689454.0
14           15  ...            1328029.0
15            -  ...             930422.0

[16 rows x 7 columns]

/tmp/ipykernel_11897/2335602178.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text)

user-Agent tells the server: request is coming from a browser”
and not a bot


requests is a library and get is a function

In [53]:
# len function
df = pd.read_csv('/content/sample_data/sales1.csv')
len(df)

600

In [54]:
# DataFrame attributes [returns information]
# columns attribute
df = pd.read_csv('/content/sample_data/sales1.csv')
print(df.columns)

Index(['Order ID', 'Customer Name', 'Product', 'Quantity'], dtype='object')

In [55]:
# printing columns inside the list
df = pd.read_csv('/content/sample_data/sales1.csv')
print(list(df.columns))

['Order ID', 'Customer Name', 'Product', 'Quantity']

In [56]:
# shape attribute
print(df.shape)
# output will be tuple and the 1st value is rows and 2nd value is columns

(600, 4)

In [57]:
# To know the total number of rows
print(df.shape[0])

600

In [58]:
# To know the total number of columns
print(df.shape[1])

4

In [59]:
# size attribute
print(df.size)
# row count x row columns (600 x 4)

2400

In [60]:
# dtypes [To know the columnwise data type]
print(df.dtypes)

Order ID          int64
Customer Name    object
Product          object
Quantity          int64
dtype: object

In [61]:
# empty attribute [This attribute check DataFrame is empty or not]
print(df.empty)

False

In [62]:
df = DataFrame()
print(df.empty)

True

In [65]:
# Index attribute
df = pd.read_csv('/content/sample_data/sales1.csv')
print(df.index)

RangeIndex(start=0, stop=600, step=1)

In [67]:
# values attribute
df = pd.read_csv('/content/sample_data/sales1.csv')
df.values

array([[166837, 'Veeru', '34in Ultrawide Monitor', 2],
       [166838, 'Tarun', 'Samsung m10', 3],
       [166839, 'Kedar', '20in Monitor', 1],
       ...,
       [167405, 'Venu', 'Flatscreen TV', 1],
       [167406, 'Siddhu', 'Samsung m20', 2],
       [167407, 'Tarun', 'LG Washing Machine', 1]], dtype=object)

In [69]:
# T attribute is used to transpose rows as columns and vice versa
df = pd.read_csv('/content/sample_data/sales1.csv')
df.T

                                  0    ...                 599
Order ID                       166837  ...              167407
Customer Name                   Veeru  ...               Tarun
Product        34in Ultrawide Monitor  ...  LG Washing Machine
Quantity                            2  ...                   1

[4 rows x 600 columns]

Function read.csv, returns an object(either Series or DataFrame object) in which data is stored

In [70]:
# DataFrame Methods [Methods perform operations]
# Head method
df = pd.read_csv('/content/sample_data/sales1.csv')
df.head()

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [71]:
# Head method
df = pd.read_csv('/content/sample_data/sales1.csv')
df.head(3)

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1

In [72]:
# Tail method
df = pd.read_csv('/content/sample_data/sales1.csv')
df.tail()

     Order ID Customer Name             Product  Quantity
595    167403        Balaji  Macbook Pro Laptop         1
596    167404       Lavanya     ThinkPad Laptop         1
597    167405          Venu       Flatscreen TV         1
598    167406        Siddhu         Samsung m20         2
599    167407         Tarun  LG Washing Machine         1

In [73]:
df = pd.read_csv('/content/sample_data/sales1.csv')
df.tail(3)

     Order ID Customer Name             Product  Quantity
597    167405          Venu       Flatscreen TV         1
598    167406        Siddhu         Samsung m20         2
599    167407         Tarun  LG Washing Machine         1

In [74]:
# Slicing method
df = pd.read_csv('/content/sample_data/sales1.csv')
df[11:21]

    Order ID Customer Name                     Product  Quantity
11    166848       Karteek          Macbook Pro Laptop         1
12    166849        Shahid             ThinkPad Laptop         1
13    166849        Siddhu      27in 4K Gaming Monitor         1
14    166850  Jaya Chandra  Bose SoundSport Headphones         1
15    166851  Jaya Chandra          Macbook Pro Laptop         1
16    166852     Madhurima                   iPhone 7s         2
17    166853         Kedar                 Samsung m10         1
18    166854         Tarun                    iPhone 7         1
19    166855       Sumanth                 Samsung m10         2
20    166856   Mallikarjun            Wired Headphones         1

In [75]:
# Info method [gives all teh information of DataFrame]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       600 non-null    int64
 1   Customer Name  600 non-null    object
 2   Product        600 non-null    object
 3   Quantity       600 non-null    int64
dtypes: int64(2), object(2)
memory usage: 18.9+ KB

While creating a DataFrame empty cells will be filled with NAN values automatically

In [76]:
# count method return actual values and ignores null values
df.count()

Order ID         600
Customer Name    600
Product          600
Quantity         600
dtype: int64

In [77]:
# describe method
df.describe()

            Order ID    Quantity
count     600.000000  600.000000
mean   167122.751667    1.481667
std       164.948568    0.683454
min    166837.000000    1.000000
25%    166980.750000    1.000000
50%    167120.500000    1.000000
75%    167266.250000    2.000000
max    167409.000000    3.000000

In [78]:
# after decimal if we require only one zero then
df.describe().round(1)

       Order ID  Quantity
count     600.0     600.0
mean   167122.8       1.5
std       164.9       0.7
min    166837.0       1.0
25%    166980.8       1.0
50%    167120.5       1.0
75%    167266.2       2.0
max    167409.0       3.0

In [80]:
# To get nunique in list data structure
a = [1,2,3,4,4,4,1,2,3]
print(set(a))
print(len(set(a)))

{1, 2, 3, 4}
4

In [81]:
# nunique method
df = pd.read_csv('/content/sample_data/sales1.csv')
df.nunique()

Order ID         573
Customer Name     23
Product           21
Quantity           3
dtype: int64

In [83]:
# accessing single column from a dataframe
df = pd.read_csv('/content/sample_data/sales1.csv')
df['Customer Name']

0        Veeru
1        Tarun
2        Kedar
3      Lavanya
4         Venu
        ...
595     Balaji
596    Lavanya
597       Venu
598     Siddhu
599      Tarun
Name: Customer Name, Length: 600, dtype: object

In [84]:
df.Product

0      34in Ultrawide Monitor
1                 Samsung m10
2                20in Monitor
3                   iPhone 11
4          Macbook Pro Laptop
                ...
595        Macbook Pro Laptop
596           ThinkPad Laptop
597             Flatscreen TV
598               Samsung m20
599        LG Washing Machine
Name: Product, Length: 600, dtype: object

In [86]:
# accessing 2 columns--> for this we need to provide list of columns
df[['Customer Name', 'Product']]

    Customer Name                 Product
0           Veeru  34in Ultrawide Monitor
1           Tarun             Samsung m10
2           Kedar            20in Monitor
3         Lavanya               iPhone 11
4            Venu      Macbook Pro Laptop
..            ...                     ...
595        Balaji      Macbook Pro Laptop
596       Lavanya         ThinkPad Laptop
597          Venu           Flatscreen TV
598        Siddhu             Samsung m20
599         Tarun      LG Washing Machine

[600 rows x 2 columns]

If we access a single columns the return type is Series

If we access a multiple columns the return type is DataFrame

In [87]:
# rearranging the column names
df[['Product', 'Customer Name', 'Order ID', 'Quantity']]

                    Product Customer Name  Order ID  Quantity
0    34in Ultrawide Monitor         Veeru    166837         2
1               Samsung m10         Tarun    166838         3
2              20in Monitor         Kedar    166839         1
3                 iPhone 11       Lavanya    166840         3
4        Macbook Pro Laptop          Venu    166841         2
..                      ...           ...       ...       ...
595      Macbook Pro Laptop        Balaji    167403         1
596         ThinkPad Laptop       Lavanya    167404         1
597           Flatscreen TV          Venu    167405         1
598             Samsung m20        Siddhu    167406         2
599      LG Washing Machine         Tarun    167407         1

[600 rows x 4 columns]

In [90]:
# Reanaming the column and index
# Reanme method
list(df.columns)

['Order ID', 'Customer Name', 'Product', 'Quantity']

In [91]:
for values in list(df.columns):
  print(values)

Order ID
Customer Name
Product
Quantity

columns attribute return type is always list and not set as insertion order is fixed

We have to use python dictionary to specify old column as key and new
column as value.

In [92]:
# our old columns
list(df.columns)

['Order ID', 'Customer Name', 'Product', 'Quantity']

In [94]:
new_columns = {'Order ID': 'ord_id', 'Customer Name': 'cus_name', 'Product': 'prod', 'Quantity': 'quant'}
print(df.head().rename(columns = new_columns))

   ord_id cus_name                    prod  quant
0  166837    Veeru  34in Ultrawide Monitor      2
1  166838    Tarun             Samsung m10      3
2  166839    Kedar            20in Monitor      1
3  166840  Lavanya               iPhone 11      3
4  166841     Venu      Macbook Pro Laptop      2

In [96]:
# columns attribute  [not used in real time]
df = pd.read_csv('/content/sample_data/sales1.csv')
df.head()

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [97]:
df.columns = ['ord_id', 'cus_name','prod', 'quant']
df.head(2)

   ord_id cus_name                    prod  quant
0  166837    Veeru  34in Ultrawide Monitor      2
1  166838    Tarun             Samsung m10      3

while using the columns attribute to change the column names the new column names should match the number of existing columns or else we will have an error

In [98]:
df.columns = ['ord_id', 'cus_name','prod']
df.head(2)

ValueError: Length mismatch: Expected axis has 4 elements, new values have 3 elements

using rename method we can even change the index of the DataFrame

In [11]:
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
i = {0:1,1:2,2:3,3:4}
df = pd.DataFrame(a)
print(df.rename(index = i))

   order_id customer_name   product
1         1             M    iphone
2         2             P       sam
3         3             D      oppo
4         4             P  micromax

In [13]:
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
i = [1,2,3,4]
df = pd.DataFrame(a, index = i)
print(df)

   order_id customer_name   product
1         1             M    iphone
2         2             P       sam
3         3             D      oppo
4         4             P  micromax

In [21]:
# index attribute
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
df = pd.DataFrame(a)
print(df.index = [1,2,3,4])

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (218879061.py, line 9)

In [22]:
# index attribute
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
df = pd.DataFrame(a)
df.index = [1,2,3,4]
print(df)

   order_id customer_name   product
1         1             M    iphone
2         2             P       sam
3         3             D      oppo
4         4             P  micromax

In [23]:
# changing column names and index in DF using attribute
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
df = pd.DataFrame(a)
df.index = [1,2,3,4]
df.columns =['ord_id','cus_name','prod']
print(df)

   ord_id cus_name      prod
1       1        M    iphone
2       2        P       sam
3       3        D      oppo
4       4        P  micromax

In [25]:
# We can change the index using range this is used when the dataset is large
import pandas as pd
df = pd.read_csv('/content/sample_data/sales3.csv')
df.head()

   ord id cust name  cust id                   prod name  prod cost
0  192837     Veeru        3                   LG Mobile      65999
1  192838   Neelima       19        Apple iPad 10.2-inch      63000
2  192839    Balaji       12      34in Ultrawide Monitor      75999
3  192840    Shahid       20                   iPhone 11      60000
4  192841     Vinay       10  Bose SoundSport Headphones      69999

In [26]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales3.csv')
df.shape

(30, 5)

In [28]:
r = range(10,40)
df.index = r
df.head()

    ord id cust name  cust id                   prod name  prod cost
10  192837     Veeru        3                   LG Mobile      65999
11  192838   Neelima       19        Apple iPad 10.2-inch      63000
12  192839    Balaji       12      34in Ultrawide Monitor      75999
13  192840    Shahid       20                   iPhone 11      60000
14  192841     Vinay       10  Bose SoundSport Headphones      69999

In [31]:
# converting column names from lower case to upper case
# To apply upper method we have to call the str attribute
# As upper is a method in string and not list
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
df = pd.DataFrame(a)
df.columns = df.columns.str.upper()
df

   ORDER_ID CUSTOMER_NAME   PRODUCT
0         1             M    iphone
1         2             P       sam
2         3             D      oppo
3         4             P  micromax

In [35]:
# As upper is a method in string and not list
df.columns

Index(['ORDER_ID', 'CUSTOMER_NAME', 'PRODUCT'], dtype='object')

In [36]:
df.columns.upper()

AttributeError: 'Index' object has no attribute 'upper'

In [37]:
df.columns.str.upper()

Index(['ORDER_ID', 'CUSTOMER_NAME', 'PRODUCT'], dtype='object')

In [39]:
df.columns = df.columns.str.lower()
df

   order_id customer_name   product
0         1             M    iphone
1         2             P       sam
2         3             D      oppo
3         4             P  micromax

In [41]:
df.columns = df.columns.str.title()
df

   Order_Id Customer_Name   Product
0         1             M    iphone
1         2             P       sam
2         3             D      oppo
3         4             P  micromax

String is an attribute in DataFrame.

Inplace parameter
Inplace is a parameter for DataFrame methods like rename(p, inplace), drop(p, inplace), sort_values(p, inplace) and set_index(p, inplace)

The above methods will create a new dataframe whenver they are used instead of making changes on existing DataFrame.

inplace parameter will avoid creating new DataFrame

When we provide inplace parameter as True changes will apply on existing DataFrame

In [44]:
import pandas as pd
a = {
'order_id': [1,2,3,4],
'customer_name': ['M', 'P', 'D', 'P'],
'product': ['iphone','sam','oppo','micromax']
}
col = {'order_id': 'ord_id', 'customer_name':'cus_name', 'product':'product'}
df = pd.DataFrame(a)
df.rename(columns = col, inplace = True)
df

   ord_id cus_name   product
0       1        M    iphone
1       2        P       sam
2       3        D      oppo
3       4        P  micromax

to_csv is a method in DataFrame
If we want to import a DF then we use it
df.to_csv(file_name)

Handling missing or NAN values

NAN data type is float

if the file loaded has missing values then the missing values are automatically considered as NaN values

None is a Python object.
NaN is a Pandas objects. Both represent missing data

In [45]:
import pandas as pd
df = pd.read_csv('/content/sample_data/fruits1.csv')
df

     Order Id  Apples  Orange  Banana
0       16723     9.0     NaN     6.0
1       16724    12.0    12.0     6.0
2       16725     9.0     NaN     NaN
3       16726    12.0     NaN    24.0
4       16727    30.0     8.0    10.0
..        ...     ...     ...     ...
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
148     16871    24.0     NaN    10.0
149     16872     5.0    30.0    10.0

[150 rows x 4 columns]

isna() and isnull() methods both are used to check NaN values in DataFrame

If missing values are available then it returns True if not False

In [46]:
df.isna()

     Order Id  Apples  Orange  Banana
0       False   False    True   False
1       False   False   False   False
2       False   False    True    True
3       False   False    True   False
4       False   False   False   False
..        ...     ...     ...     ...
145     False   False   False   False
146     False   False   False   False
147     False   False   False   False
148     False   False    True   False
149     False   False   False   False

[150 rows x 4 columns]

In [47]:
# To know the column wise missing values we use sum method
df.isna().sum()

Order Id     0
Apples      16
Orange      16
Banana      21
dtype: int64

In [48]:
# Counting the missing values in each column with percentage
df.isna().sum()/len(df)

Order Id    0.000000
Apples      0.106667
Orange      0.106667
Banana      0.140000
dtype: float64

In [53]:
# dropna() method - Handling missing values
# dropna method drops the entire rows where atleast one missing value is present
print(df.dropna())

     Order Id  Apples  Orange  Banana
1       16724    12.0    12.0     6.0
4       16727    30.0     8.0    10.0
5       16728     6.0     6.0    12.0
6       16729    12.0    24.0     9.0
7       16730    24.0     6.0     8.0
..        ...     ...     ...     ...
143     16866    12.0    10.0    10.0
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
149     16872     5.0    30.0    10.0

[105 rows x 4 columns]

In [54]:
print(df.dropna().isna().sum())

Order Id    0
Apples      0
Orange      0
Banana      0
dtype: int64

Applying one method on another is called as method chaining

In [56]:
s = 'Hello Hello Hello How are you'
print(s.count('Hello'))
print(s.upper().count('Hello'))

3
0

In [61]:
# Converting float column type into int data type
# astype(int)
df.dropna().head()

   Order Id  Apples  Orange  Banana
1     16724    12.0    12.0     6.0
4     16727    30.0     8.0    10.0
5     16728     6.0     6.0    12.0
6     16729    12.0    24.0     9.0
7     16730    24.0     6.0     8.0

In [60]:
df.dropna().astype(int).head()

   Order Id  Apples  Orange  Banana
1     16724      12      12       6
4     16727      30       8      10
5     16728       6       6      12
6     16729      12      24       9
7     16730      24       6       8

In [62]:
df['Apples']

0       9.0
1      12.0
2       9.0
3      12.0
4      30.0
       ...
145    24.0
146     8.0
147     5.0
148    24.0
149     5.0
Name: Apples, Length: 150, dtype: float64

In [64]:
df.dropna().astype(int)['Apples'].sum()

np.int64(1414)

missing values can be handled with following methods
dropna(), replace(), fillna()

In [77]:
# dropna(inplace = True)
import pandas as pd
df = pd.read_csv('/content/sample_data/fruits1.csv')
df.dropna(inplace = True)
df

     Order Id  Apples  Orange  Banana
1       16724    12.0    12.0     6.0
4       16727    30.0     8.0    10.0
5       16728     6.0     6.0    12.0
6       16729    12.0    24.0     9.0
7       16730    24.0     6.0     8.0
..        ...     ...     ...     ...
143     16866    12.0    10.0    10.0
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
149     16872     5.0    30.0    10.0

[105 rows x 4 columns]

In [78]:
# without inplace = True
import pandas as pd
df = pd.read_csv('/content/sample_data/fruits1.csv')
df.dropna()
df

     Order Id  Apples  Orange  Banana
0       16723     9.0     NaN     6.0
1       16724    12.0    12.0     6.0
2       16725     9.0     NaN     NaN
3       16726    12.0     NaN    24.0
4       16727    30.0     8.0    10.0
..        ...     ...     ...     ...
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
148     16871    24.0     NaN    10.0
149     16872     5.0    30.0    10.0

[150 rows x 4 columns]

In [85]:
# fillna() method- Handling missing values
df = pd.read_csv('/content/sample_data/fruits1.csv')
df.fillna(0,inplace = True)
df.astype(int)

     Order Id  Apples  Orange  Banana
0       16723       9       0       6
1       16724      12      12       6
2       16725       9       0       0
3       16726      12       0      24
4       16727      30       8      10
..        ...     ...     ...     ...
145     16868      24      12       6
146     16869       8       8      12
147     16870       5      30      30
148     16871      24       0      10
149     16872       5      30      10

[150 rows x 4 columns]

In [86]:
# fillna() method- using mean value
df = pd.read_csv('/content/sample_data/fruits1.csv')
df.isna().sum()

Order Id     0
Apples      16
Orange      16
Banana      21
dtype: int64

In [89]:
df['Apples'].mean().round()

np.float64(13.0)

In [94]:
df['Apples'] = df['Apples'].fillna(df['Apples'].mean().round())
df['Orange'] = df['Orange'].fillna(df['Orange'].mean().round())
df['Banana'] = df['Banana'].fillna(df['Banana'].mean().round())
df

     Order Id  Apples  Orange  Banana
0       16723     9.0    14.0     6.0
1       16724    12.0    12.0     6.0
2       16725     9.0    14.0    13.0
3       16726    12.0    14.0    24.0
4       16727    30.0     8.0    10.0
..        ...     ...     ...     ...
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
148     16871    24.0    14.0    10.0
149     16872     5.0    30.0    10.0

[150 rows x 4 columns]

In [16]:
# replacing NaN values with specific value
import pandas as pd
import numpy as np
a = [
[1, 'M', 'iphone', 1000],
[2, 'P', 'sam', 2000],
[3,np.nan,'oppo',3000],
[4, 'L','Max',np.nan]
]
col = ['ord_id', 'cus_name', 'product', 'salary']
df = pd.DataFrame(a, columns = col)
df = df.replace(np.nan, 0)
df

   ord_id cus_name product  salary
0       1        M  iphone  1000.0
1       2        P     sam  2000.0
2       3        0    oppo  3000.0
3       4        L     Max     0.0

In [19]:
# When there is no return statment we don't need use print function
# If we use print function when no return statment we will have None as output
def balance():
  print('manoj')
b = balance()
print(b)

manoj
None

In [20]:
# When there is return statment we need to use print function
def balance():
  print('manoj')
  return 'good_boy'
b = balance()
print(b)

manoj
good_boy

In [21]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales1.csv')
df.head()

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [23]:
# Selecting first 2 columns of the dataframe
df[['Order ID', 'Customer Name']].head()

   Order ID Customer Name
0    166837         Veeru
1    166838         Tarun
2    166839         Kedar
3    166840       Lavanya
4    166841          Venu

sum is a method in Series object and not DataFrame object

In [32]:
# Selecting specific customer from a dataframe
condition = df['Customer Name'] == 'Venu'
condition.head()

0    False
1    False
2    False
3    False
4     True
Name: Customer Name, dtype: bool

In [34]:
df[condition].head()

    Order ID Customer Name                     Product  Quantity
4     166841          Venu          Macbook Pro Laptop         2
5     166842          Venu  Bose SoundSport Headphones         2
10    166847          Venu                 Samsung m10         2
28    166864          Venu        USB-C Charging Cable         1
32    166868          Venu                    iPhone 7         1

In [28]:
df[condition].shape

(27, 4)

We have a total of 27 records

In [36]:
condition = df['Customer Name'] == 'Manu'
condition.head()
df[condition]

Empty DataFrame
Columns: [Order ID, Customer Name, Product, Quantity]
Index: []

When we give wrong name that is not in the data, we will get empty DataFrame

In [38]:
# accessing specific product from the dataframe
condition = df['Product'] == 'iPhone 7'
condition.head()

0    False
1    False
2    False
3    False
4    False
Name: Product, dtype: bool

In [40]:
df[condition].head()

    Order ID Customer Name   Product  Quantity
18    166854         Tarun  iPhone 7         1
27    166863       Karteek  iPhone 7         1
31    166867    Nireekshan  iPhone 7         1
32    166868          Venu  iPhone 7         1
44    166880        Siddhu  iPhone 7         2

In [41]:
df[condition].shape

(22, 4)

We can select columns from the dataframe using loc and iloc indexers

In [42]:
# iloc and loc indexers
import pandas as pd
df = pd.read_csv('/content/sample_data/sales1.csv')
df.head()

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [44]:
# sample method is used to access a random row in a dataframe
df.sample()

     Order ID Customer Name           Product  Quantity
125    166960       Pradhan  Wired Headphones         3

Row differs every time we access

In [45]:
# Selecting a single row
# If we select one row then it returns a Series
df.iloc[0]

Order ID                         166837
Customer Name                     Veeru
Product          34in Ultrawide Monitor
Quantity                              2
Name: 0, dtype: object

In [46]:
df.iloc[-1]

Order ID                     167407
Customer Name                 Tarun
Product          LG Washing Machine
Quantity                          1
Name: 599, dtype: object

iloc[single integer value]

iloc[LHS , RHS] --> Similar to slicing

iloc[: , columns] --> to access all rows

iloc[: , :] --> To access all rows and columns

In [47]:
a = [1,2,3,4,5]
print(a[0:3])

[1, 2, 3]

In [48]:
#To access all the values
print(a[:])

[1, 2, 3, 4, 5]

In [50]:
# To access all rows and columns of a dataframe
df.iloc[:,:].head()

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [51]:
df.iloc[:,0].head(2)

0    166837
1    166838
Name: Order ID, dtype: int64

In [52]:
df.iloc[:,1].head(2)

0    Veeru
1    Tarun
Name: Customer Name, dtype: object

In [53]:
df.columns

Index(['Order ID', 'Customer Name', 'Product', 'Quantity'], dtype='object')

In [54]:
for columns in df.columns:
  print(columns)

Order ID
Customer Name
Product
Quantity

In [55]:
# To print 1st 5 rows without head() method
df.iloc[0:5]

   Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [56]:
# To access rows form 10 - 14
df.iloc[10:15]

    Order ID Customer Name                     Product  Quantity
10    166847          Venu                 Samsung m10         2
11    166848       Karteek          Macbook Pro Laptop         1
12    166849        Shahid             ThinkPad Laptop         1
13    166849        Siddhu      27in 4K Gaming Monitor         1
14    166850  Jaya Chandra  Bose SoundSport Headphones         1

In [57]:
df.iloc[0:5, 1]

0      Veeru
1      Tarun
2      Kedar
3    Lavanya
4       Venu
Name: Customer Name, dtype: object

Setting a particular column of a dataframe as an index

In [59]:
# Set_index method
import pandas as pd
df = pd.read_csv('/content/sample_data/sales1.csv')
df = df.set_index('Product')
df.head()

                        Order ID Customer Name  Quantity
Product
34in Ultrawide Monitor    166837         Veeru         2
Samsung m10               166838         Tarun         3
20in Monitor              166839         Kedar         1
iPhone 11                 166840       Lavanya         3
Macbook Pro Laptop        166841          Venu         2

While selecting a product column as an index If a product is missing from the product column that will be represented with Nan


However, before setting the product column as an index we have to process the column by dropping it or performing necessary operations

In [63]:
# Setting index as a Product name and selecting Product
# This will access all the iphone 11 available in the data
import pandas as pd
df = pd.read_csv('/content/sample_data/sales1.csv')
df = df.set_index('Product')
df.loc['iPhone 11'].head()

           Order ID Customer Name  Quantity
Product
iPhone 11    166840       Lavanya         3
iPhone 11    166846        Siddhu         1
iPhone 11    166858    Chaithanya         1
iPhone 11    166877       Neelima         1
iPhone 11    166904       Lavanya         1

In [66]:
# Setting index as a Product name and selecting 2 Product
df = pd.read_csv('/content/sample_data/sales1.csv')
df = df.set_index('Product')
df.loc[['iPhone 11','20in Monitor']].head()

           Order ID Customer Name  Quantity
Product
iPhone 11    166840       Lavanya         3
iPhone 11    166846        Siddhu         1
iPhone 11    166858    Chaithanya         1
iPhone 11    166877       Neelima         1
iPhone 11    166904       Lavanya         1

Setting index as a Product name and selecting a couple of product
names with Product ID and Customer name

In [71]:
df = pd.read_csv('/content/sample_data/sales1.csv')
df = df.set_index('Product')
df = df.loc[['iPhone 11','20in Monitor'] ,['Order ID','Customer Name']]
df.head()

           Order ID Customer Name
Product
iPhone 11    166840       Lavanya
iPhone 11    166846        Siddhu
iPhone 11    166858    Chaithanya
iPhone 11    166877       Neelima
iPhone 11    166904       Lavanya

In [76]:
df = pd.read_csv('/content/sample_data/sales1.csv')
df = df.set_index('Product')
df = df.loc[['iPhone 11','20in Monitor'],'Order ID' : 'Quantity']
df.head()

           Order ID Customer Name  Quantity
Product
iPhone 11    166840       Lavanya         3
iPhone 11    166846        Siddhu         1
iPhone 11    166858    Chaithanya         1
iPhone 11    166877       Neelima         1
iPhone 11    166904       Lavanya         1

Boolean / Logical indexing

Based on conditions we can get rows and columns from Dataframe

In [78]:
# Boolean/Logical indexing. Below code is widely used
df = pd.read_csv('/content/sample_data/sales1.csv')
condition = df['Customer Name'] == 'Lavanya'
df.loc[condition].head()

     Order ID Customer Name                 Product  Quantity
3      166840       Lavanya               iPhone 11         3
26     166862       Lavanya  34in Ultrawide Monitor         1
46     166882       Lavanya             Samsung m20         1
68     166904       Lavanya               iPhone 11         1
150    166981       Lavanya             Samsung m10         3

In [79]:
# Boolean/Logical indexing. This code is not widely used
df = pd.read_csv('/content/sample_data/sales1.csv')
condition = df['Customer Name'] == 'Lavanya'
df[condition].head()

     Order ID Customer Name                 Product  Quantity
3      166840       Lavanya               iPhone 11         3
26     166862       Lavanya  34in Ultrawide Monitor         1
46     166882       Lavanya             Samsung m20         1
68     166904       Lavanya               iPhone 11         1
150    166981       Lavanya             Samsung m10         3

In [81]:
# Select rows with specific product with columns between Order id and Product
condition = df['Customer Name']== 'Lavanya'
df.loc[condition, 'Order ID' : 'Product'].head()

     Order ID Customer Name                 Product
3      166840       Lavanya               iPhone 11
26     166862       Lavanya  34in Ultrawide Monitor
46     166882       Lavanya             Samsung m20
68     166904       Lavanya               iPhone 11
150    166981       Lavanya             Samsung m10

In [3]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales1.csv')
condition = df['Customer Name'] == 'Lavanya'
df.loc[condition, ['Order ID', 'Product']].head()
# here the condition is row selection and the ['Order ID', 'Product'] is column selection

     Order ID                 Product
3      166840               iPhone 11
26     166862  34in Ultrawide Monitor
46     166882             Samsung m20
68     166904               iPhone 11
150    166981             Samsung m10

iloc indexer --> Takes intigers as input


loc indexer --> Takes labels and and Boolean conditions as input

Loc indexer is used for:
1) selecting rows by label/index
2) selecting rows using boolean condition

DataFrame-Filtering

data filtering is dones in 2 ways
1) using relational operators --> using single condition or multiple conditions
2) using iloc and loc

In [5]:
# Filtering
a = [1,2,3,4,5]
for values in a:
  if values <3:
    print(values)

1
2

In [6]:
# Filtering
a = [1,2,3,4,5]
for values in a:
  if values == 3:
    print(values)

3

In [8]:
# Filtering using 2 conditions
a = [1,2,3,4,5]
for values in a:
  if values >2 and values <5:
    print(values)

3
4

In [12]:
# Filtering DataFrame using relational operator: single condition
df = pd.read_csv('/content/sample_data/sales4.csv')
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
0,1023,Venki,15,27in FHD Monitor,59000
1,1024,Chaithanya,14,iPhone 11,69000
2,1025,Shahid,20,Bose SoundSport Headphones,65999
3,1026,Veeru,3,Apple iPad 10.2-inch,63999
4,1027,Venu,23,Google Phone,63999

In [17]:
condition = df['Product_Cost']> 65000
df[condition]

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
1,1024,Chaithanya,14,iPhone 11,69000
2,1025,Shahid,20,Bose SoundSport Headphones,65999
11,1034,Tarun,11,Samsung Galaxy S20,69999
13,1036,Chaithanya,14,LG ThinQ Refrigerator,69999
17,1040,Sumanth,22,iPhone 8,65999
...,...,...,...,...,...
299982,301005,Tarun,11,Samsung Galaxy S20,69000
299983,301006,Shafi,25,27in 4K Gaming Monitor,69000
299985,301008,Venki,15,Apple Airpods Headphones,65999
299988,301011,Venki,15,Google Phone,65999
299990,301013,Balaji,12,iPhone 11,65999

In [24]:
# Filtering DataFrame by using relational operator: Multiple conditions
df = pd.read_csv('/content/sample_data/sales4.csv')
condition1 = df['Product_Cost'] > 50000
condition2 = df['Product_Cost'] < 60000
df[condition1 & condition2]

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
0,1023,Venki,15,27in FHD Monitor,59000
8,1031,Kedar,2,20in Monitor,55999
12,1035,Kedar,2,Google Phone,55999
14,1037,Nireekshan,1,Apple Airpods Headphones,55999
22,1045,Lavanya,16,iPhone 7s,51999
...,...,...,...,...,...
299993,301016,Siddhu,18,iPhone 9,59000
299994,301017,Kedar,2,ThinkPad Laptop,55999
299995,301018,Karteek,4,Apple iPad 10.2-inch,51999
299996,301019,Veeru,3,Macbook Pro Laptop,51999
299999,301022,Pradhan,17,34in Ultrawide Monitor,55000

Key rule (VERY important)

When using & or | --> or in Pandas:

✅ ALWAYS wrap conditions in parentheses

In [27]:
df = pd.read_csv('/content/sample_data/sales4.csv')
condition = (df['Product_Cost'] > 50000) & (df['Product_Cost'] < 60000)
df[condition].head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
0,1023,Venki,15,27in FHD Monitor,59000
8,1031,Kedar,2,20in Monitor,55999
12,1035,Kedar,2,Google Phone,55999
14,1037,Nireekshan,1,Apple Airpods Headphones,55999
22,1045,Lavanya,16,iPhone 7s,51999

In [29]:
df = pd.read_csv('/content/sample_data/sales4.csv')
condition = (df['Customer_Name'] == 'Venki') & (df['Product_Name'] == '27in FHD Monitor')
df[condition]

        Order_Id Customer_Name  Customer_Id      Product_Name  Product_Cost
0           1023         Venki           15  27in FHD Monitor         59000
647         1670         Venki           15  27in FHD Monitor         50000
723         1746         Venki           15  27in FHD Monitor         50000
1202        2225         Venki           15  27in FHD Monitor         60000
1713        2736         Venki           15  27in FHD Monitor         50000
...          ...           ...          ...               ...           ...
296397    297420         Venki           15  27in FHD Monitor         55000
296641    297664         Venki           15  27in FHD Monitor         65999
298229    299252         Venki           15  27in FHD Monitor         65999
298335    299358         Venki           15  27in FHD Monitor         69999
298882    299905         Venki           15  27in FHD Monitor         55999

[610 rows x 5 columns]

We can filter dataframe using loc and iloc indexers and the main benifit id using these indexers is that the execution is fast compared to relational operators

In [1]:
# Filtering by using iloc
import pandas as pd
df = pd.read_csv('/content/sample_data/sales4.csv')
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
0,1023,Venki,15,27in FHD Monitor,59000
1,1024,Chaithanya,14,iPhone 11,69000
2,1025,Shahid,20,Bose SoundSport Headphones,65999
3,1026,Veeru,3,Apple iPad 10.2-inch,63999
4,1027,Venu,23,Google Phone,63999

In [3]:
df.iloc[:5,:-1]

   Order_Id Customer_Name  Customer_Id                Product_Name
0      1023         Venki           15            27in FHD Monitor
1      1024    Chaithanya           14                   iPhone 11
2      1025        Shahid           20  Bose SoundSport Headphones
3      1026         Veeru            3        Apple iPad 10.2-inch
4      1027          Venu           23                Google Phone

In [4]:
df.iloc[:5,-1]

0    59000
1    69000
2    65999
3    63999
4    63999
Name: Product_Cost, dtype: int64

select DataFrame by providing rows position and column name

syntax: df.loc[rows, columns]

In [9]:
df = pd.read_csv('/content/sample_data/sales4.csv')
col = ['Customer_Name', 'Product_Name']
row = df.index[0:5]
df.loc[row,col]

  Customer_Name                Product_Name
0         Venki            27in FHD Monitor
1    Chaithanya                   iPhone 11
2        Shahid  Bose SoundSport Headphones
3         Veeru        Apple iPad 10.2-inch
4          Venu                Google Phone

In [10]:
df = pd.read_csv('/content/sample_data/sales4.csv')
col = ['Customer_Name', 'Product_Name']
df.loc[0:5,col]

  Customer_Name                Product_Name
0         Venki            27in FHD Monitor
1    Chaithanya                   iPhone 11
2        Shahid  Bose SoundSport Headphones
3         Veeru        Apple iPad 10.2-inch
4          Venu                Google Phone
5        Daniel      Samsung Galaxy S9 Plus

.loc uses labels (which can be integers if your index is integer-based)

.iloc uses integer positions only

df.loc[0:5]    # includes 5 ✅
df.iloc[0:5]   # excludes 5 ❌

In [14]:
df.loc[0:5,'Product_Name']

0              27in FHD Monitor
1                     iPhone 11
2    Bose SoundSport Headphones
3          Apple iPad 10.2-inch
4                  Google Phone
5        Samsung Galaxy S9 Plus
Name: Product_Name, dtype: object

While using '&' operator we have to ensure both the conditions are true or else there will be no result or output

if it is or operator '|' whatever condition is true it will print that result

In [17]:
# Selecting multiple values of a column
import pandas as pd
df = pd.read_csv('/content/sample_data/sales4.csv')
condition = (df['Product_Name'] == 'Google Phone') & (df['Customer_Name'] == 'Venki')
df.loc[condition].head() # always better at functionality
# As we can apply filter rows and select specific columns at a time

      Order_Id Customer_Name  Customer_Id  Product_Name  Product_Cost
123       1146         Venki           15  Google Phone         55999
1457      2480         Venki           15  Google Phone         69000
1508      2531         Venki           15  Google Phone         55000
1849      2872         Venki           15  Google Phone         61000
1908      2931         Venki           15  Google Phone         60000

'Or' operator gives mixed results wherever the condition seems to match(for instance we have given 2 conditions) it will give results of both the conditions.

In [21]:
condition = (df['Customer_Id'] == 1) | (df['Product_Name'] == 'iPhone 11')
df.loc[condition].head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
1,1024,Chaithanya,14,iPhone 11,69000
6,1029,Venu,23,iPhone 11,61000
14,1037,Nireekshan,1,Apple Airpods Headphones,55999
26,1049,Shahid,20,iPhone 11,65999
34,1057,Tarun,11,iPhone 11,55999

In [20]:
condition = (df['Customer_Id'] == 1) & (df['Product_Name'] == 'iPhone 11')
df.loc[condition].head()

      Order_Id Customer_Name  Customer_Id Product_Name  Product_Cost
821       1844    Nireekshan            1    iPhone 11         63999
1086      2109    Nireekshan            1    iPhone 11         65000
1529      2552    Nireekshan            1    iPhone 11         55000
1539      2562    Nireekshan            1    iPhone 11         61000
1676      2699    Nireekshan            1    iPhone 11         65000

isin is a predefined method in Series object

We are not using isin() in real-time

In [25]:
# isin() method
# Accessing single product
df['Product_Name'].isin(['iPhone 11'])
df[df['Product_Name'].isin(['iPhone 11'])].head()

    Order_Id Customer_Name  Customer_Id Product_Name  Product_Cost
1       1024    Chaithanya           14    iPhone 11         69000
6       1029          Venu           23    iPhone 11         61000
26      1049        Shahid           20    iPhone 11         65999
34      1057         Tarun           11    iPhone 11         55999
48      1071          Venu           23    iPhone 11         65999

In [28]:
# commonly used way
df = pd.read_csv('/content/sample_data/sales4.csv')
condition = df['Product_Name'] == 'iPhone 11'
df[condition].head()

    Order_Id Customer_Name  Customer_Id Product_Name  Product_Cost
1       1024    Chaithanya           14    iPhone 11         69000
6       1029          Venu           23    iPhone 11         61000
26      1049        Shahid           20    iPhone 11         65999
34      1057         Tarun           11    iPhone 11         55999
48      1071          Venu           23    iPhone 11         65999

In [35]:
# accessing multiple products
df = pd.read_csv('/content/sample_data/sales4.csv')
a = ['iPhone 11','Apple Airpods Headphones']
df['Product_Name'].isin(a)
df[df['Product_Name'].isin(a)].head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
1,1024,Chaithanya,14,iPhone 11,69000
6,1029,Venu,23,iPhone 11,61000
14,1037,Nireekshan,1,Apple Airpods Headphones,55999
20,1043,Vinay,10,Apple Airpods Headphones,61000
26,1049,Shahid,20,iPhone 11,65999

! --> not operator

In [36]:
# unique() function --> return the unique values of the column
import pandas as pd
df = pd.read_csv('/content/sample_data/sales4.csv')
pd.unique(df['Customer_Name'])

array(['Venki', 'Chaithanya', 'Shahid', 'Veeru', 'Venu', 'Daniel',
       'Shafi', 'Kedar', 'Neelima', 'Vijay', 'Tarun', 'Nireekshan',
       'Karteek', 'Sumanth', 'Mallikarjun', 'Vinay', 'Lavanya',
       'Madhurima', 'Partha', 'Siddhu', 'Jaya Chandra', 'Balaji',
       'Pradhan', 'Harsha', 'Mohan'], dtype=object)

notnull() method is accessed by using Series object

using this method we can select the DataFrame which having non NaN values.

In [39]:
# Select Non-Missing Data from DataFrame
# notnull() method
import pandas as pd
import numpy as np
a = [
[1, 'M', 'iphone', 1000],
[2, 'P', 'sam', 2000],
[3,np.nan,'oppo',3000],
[4, 'L','Max',np.nan]
]
column = ['id','name','product','price']
df = pd.DataFrame(a,columns = column)
df

   id name product   price
0   1    M  iphone  1000.0
1   2    P     sam  2000.0
2   3  NaN    oppo  3000.0
3   4    L     Max     NaN

In [42]:
# selecting the DataFrame which is having non NaN values.
df['name'].notnull()
df[df['name'].notnull()]

   id name product   price
0   1    M  iphone  1000.0
1   2    P     sam  2000.0
3   4    L     Max     NaN

In [44]:
# DataFrame- Sorting
a = [1,7,9,6,5]
a.sort()
print(a)

[1, 5, 6, 7, 9]

In [45]:
a = ['x','g','k','l','m','a','n','o','p']
a.sort()
print(a)

['a', 'g', 'k', 'l', 'm', 'n', 'o', 'p', 'x']

Sorting can be applied based on column values or index

sort_values() is used to sort by column values.

sort_index() is used to sort by index

sort_values has a return statment so its calling is assigned to a variable

In [50]:
# sort_values()
import pandas as pd
df = pd.read_csv('/content/sample_data/sales4.csv')
df = df.sort_values(by = 'Product_Cost').head()
df

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
243862,244885,Vinay,10,iPhone 7s,50000
35,1058,Jaya Chandra,21,iPhone 8,50000
23,1046,Madhurima,7,Macbook Pro Laptop,50000
18,1041,Venki,15,Samsung Galaxy S20,50000
273876,274899,Venki,15,Bose SoundSport Headphones,50000

In [77]:
# Ascending = min to max
# Ascending = False --> opposite of ascending
# Instead of false we can even provide 0
df = pd.read_csv('/content/sample_data/sales4.csv')
df = df.sort_values(by = 'Customer_Id',ascending = False).head()
df

        Order_Id Customer_Name  Customer_Id      Product_Name  Product_Cost
145501    146524         Shafi           25      Google Phone         65999
145473    146496         Shafi           25   ThinkPad Laptop         63000
145483    146506         Shafi           25     Flatscreen TV         55999
145485    146508         Shafi           25         iPhone 11         51999
145470    146493         Shafi           25  27in FHD Monitor         60000

In [78]:
df = pd.read_csv('/content/sample_data/sales4.csv')
df = df.sort_values(by = 'Customer_Id', ascending = 0).head()
df

        Order_Id Customer_Name  Customer_Id      Product_Name  Product_Cost
145501    146524         Shafi           25      Google Phone         65999
145473    146496         Shafi           25   ThinkPad Laptop         63000
145483    146506         Shafi           25     Flatscreen TV         55999
145485    146508         Shafi           25         iPhone 11         51999
145470    146493         Shafi           25  27in FHD Monitor         60000

In [82]:
# Sorting happens in alphabetic order in alphabets
df = pd.read_csv('/content/sample_data/sales4.csv')
df = df.sort_values(by = 'Customer_Name', ascending = True).head()
df

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
136196,137219,Balaji,12,LG Mobile,60000
128754,129777,Balaji,12,Samsung Galaxy S20,61000
292113,293136,Balaji,12,LG Mobile,65999
128753,129776,Balaji,12,LG ThinQ Refrigerator,65999
73777,74800,Balaji,12,Apple iPad 10.2-inch,51999

In [74]:
df = pd.read_csv('/content/sample_data/sales4.csv')
list(df['Customer_Name'].unique())

['Venki',
 'Chaithanya',
 'Shahid',
 'Veeru',
 'Venu',
 'Daniel',
 'Shafi',
 'Kedar',
 'Neelima',
 'Vijay',
 'Tarun',
 'Nireekshan',
 'Karteek',
 'Sumanth',
 'Mallikarjun',
 'Vinay',
 'Lavanya',
 'Madhurima',
 'Partha',
 'Siddhu',
 'Jaya Chandra',
 'Balaji',
 'Pradhan',
 'Harsha',
 'Mohan']

In [75]:
df = df['Customer_Name'].sort_values().unique()
df

array(['Balaji', 'Chaithanya', 'Daniel', 'Harsha', 'Jaya Chandra',
       'Karteek', 'Kedar', 'Lavanya', 'Madhurima', 'Mallikarjun', 'Mohan',
       'Neelima', 'Nireekshan', 'Partha', 'Pradhan', 'Shafi', 'Shahid',
       'Siddhu', 'Sumanth', 'Tarun', 'Veeru', 'Venki', 'Venu', 'Vijay',
       'Vinay'], dtype=object)

In [83]:
# sort_index method
import pandas as pd
d = {'Oredr_id':[1,2,3], 'Customer_name':['M', 'K', 'G'], 'Product': ['iphone','Sam','nokia']}
i = [6,2,9]
df = pd.DataFrame(d, index = i)
df.sort_index()

   Oredr_id Customer_name Product
2         2             K     Sam
6         1             M  iphone
9         3             G   nokia

There are mainly 3 steps in Groupby operation.

o Splitting the data into groups based on some criteria.

o Applying operations to each group independently.

o Combining the results.

df.shape returns a tuple --> (10,4)

df.head() returns a dataframe

df.groupby() returns a groupby object

Generally when we apply any method on DataFrame we will get the result but in case of groupby we will get another object over which we perform the operation

In [85]:
# Groupby
d = {'Product':['Sam', 'Nokia', 'Sam', 'Motorola', 'Nokia', 'Sam', 'Sam'], 'Orders': [2,4,3,4,6,7,3]}
df = pd.DataFrame(d)
df

    Product  Orders
0       Sam       2
1     Nokia       4
2       Sam       3
3  Motorola       4
4     Nokia       6
5       Sam       7
6       Sam       3

In [86]:
# Applying groupby method
df.groupby('Product')

In the above example we can see the object being returned

In [87]:
# Lets apply sum operation on the obeject returned
df.groupby('Product').sum()

          Orders
Product
Motorola       4
Nokia         10
Sam           15

In [88]:
# Applying groupby over mail id column
df = pd.read_csv('/content/sample_data/sales5.csv')
df.head()

,Order_Id,Customer_Id,Mail_Id,Product_Name,Product_Cost,Date
0,1,1,nirekshan@gmail.com,Samsung,10000,11/06/2019
1,2,2,kedar@gmail.com,iPhone 8,20000,11/06/2019
2,3,3,Daniel@gmail.com,Kindle Paper White,10000,10/31/2019
3,4,4,prasad@gmail.com,hTC mobile,15000,11/02/2019
4,5,1,nirekshan@gmail.com,Samsung,10000,11/02/2019

In [89]:
df.groupby('Mail_Id').size() # Returns count of rows per group

Mail_Id
Daniel@gmail.com       3
kedar@gmail.com        3
nirekshan@gmail.com    4
partha@gmail.com       1
prasad@gmail.com       3
shahid@gmail.com       1
dtype: int64

A Series is a 1-dimensional data structure that can store different types of data (including objects like lists), and it can be converted into a DataFrame.

In [91]:
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Date','Product_Name'])['Date'].count()
# We first group the data by Date and Product_Name.
# Then select the Date column from each group for further operations.

Date        Product_Name
09/01/2019  iPad                  1
09/02/2019  LG Washing Machine    1
09/06/2019  Kindle Paper White    2
            Sofa set              1
            iPhone 8              1
10/31/2019  Kindle Paper White    1
11/02/2019  Samsung               2
            hTC mobile            1
11/06/2019  Samsung               1
            iPhone 8              2
            iPhone 9              1
11/10/2019  hTC mobile            1
Name: Date, dtype: int64

In [99]:
# Product wise each month sales
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Product_Name','Date'])['Date'].count()

Product_Name        Date
Kindle Paper White  09/06/2019    2
                    10/31/2019    1
LG Washing Machine  09/02/2019    1
Samsung             11/02/2019    2
                    11/06/2019    1
Sofa set            09/06/2019    1
hTC mobile          11/02/2019    1
                    11/10/2019    1
iPad                09/01/2019    1
iPhone 8            09/06/2019    1
                    11/06/2019    2
iPhone 9            11/06/2019    1
Name: Date, dtype: int64

In [101]:
# customer wise each month sales
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Mail_Id','Date'])['Date'].count()

Mail_Id              Date
Daniel@gmail.com     09/06/2019    2
                     10/31/2019    1
kedar@gmail.com      09/06/2019    1
                     11/06/2019    2
nirekshan@gmail.com  09/06/2019    1
                     11/02/2019    2
                     11/06/2019    1
partha@gmail.com     11/06/2019    1
prasad@gmail.com     09/02/2019    1
                     11/02/2019    1
                     11/10/2019    1
shahid@gmail.com     09/01/2019    1
Name: Date, dtype: int64

When NaN values exist the real difference comes to play

In [103]:
import pandas as pd
import numpy as np
d = {'Oredr_id':[1,2,3], 'Customer_name':['M', 'K', 'G'], 'Product': ['iphone','Sam',np.nan]}
i = [6,2,9]
df = pd.DataFrame(d, index = i)
df

   Oredr_id Customer_name Product
6         1             M  iphone
2         2             K     Sam
9         3             G     NaN

In [107]:
df.groupby(['Customer_name','Product'])['Customer_name'].count()

Customer_name  Product
K              Sam        1
M              iphone     1
Name: Customer_name, dtype: int64

In [108]:
df.groupby(['Customer_name','Product'])['Product'].count()

Customer_name  Product
K              Sam        1
M              iphone     1
Name: Product, dtype: int64

In [113]:
df = pd.DataFrame({
    'A': ['X','X','Y'],
    'B': [1, np.nan, 1]
})
print(df)
df.groupby('A')['A'].count()

   A    B
0  X  1.0
1  X  NaN
2  Y  1.0

A
X    2
Y    1
Name: A, dtype: int64

df.groupby('A') --> Groups formed:

X → 2 rows

Y → 1 row

Now within the 2 group X and y look at column A we have 2 X and 1 y

Now within the 2 group X and y look at column B for group X we have [1, nan] and 1 y. So x = 1 and y = 1

In [111]:
df.groupby('A')['B'].count()

A
X    1
Y    1
Name: B, dtype: int64

In [114]:
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Mail_Id','Product_Name'])

In [116]:
# Customer wise product details
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Mail_Id','Product_Name'])['Product_Cost'].sum()

Mail_Id              Product_Name
Daniel@gmail.com     Kindle Paper White    20000
                     Sofa set              50000
kedar@gmail.com      iPhone 8              60000
nirekshan@gmail.com  Kindle Paper White    20000
                     Samsung               30000
partha@gmail.com     iPhone 9              30000
prasad@gmail.com     LG Washing Machine    25000
                     hTC mobile            30000
shahid@gmail.com     iPad                  70000
Name: Product_Cost, dtype: int64

In [120]:
# Customer wise product details
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Mail_Id','Product_Name'])['Product_Name'].count()

Mail_Id              Product_Name
Daniel@gmail.com     Kindle Paper White    2
                     Sofa set              1
kedar@gmail.com      iPhone 8              3
nirekshan@gmail.com  Kindle Paper White    1
                     Samsung               3
partha@gmail.com     iPhone 9              1
prasad@gmail.com     LG Washing Machine    1
                     hTC mobile            2
shahid@gmail.com     iPad                  1
Name: Product_Name, dtype: int64

In [122]:
# Now let's convert the series into DataFrame
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Mail_Id','Product_Name'],as_index = False)['Product_Cost'].sum()

               Mail_Id        Product_Name  Product_Cost
0     Daniel@gmail.com  Kindle Paper White         20000
1     Daniel@gmail.com            Sofa set         50000
2      kedar@gmail.com            iPhone 8         60000
3  nirekshan@gmail.com  Kindle Paper White         20000
4  nirekshan@gmail.com             Samsung         30000
5     partha@gmail.com            iPhone 9         30000
6     prasad@gmail.com  LG Washing Machine         25000
7     prasad@gmail.com          hTC mobile         30000
8     shahid@gmail.com                iPad         70000

In [125]:
# Let's see the customer wise product sales
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Mail_Id'], as_index = False)['Product_Cost'].sum()

               Mail_Id  Product_Cost
0     Daniel@gmail.com         70000
1      kedar@gmail.com         60000
2  nirekshan@gmail.com         50000
3     partha@gmail.com         30000
4     prasad@gmail.com         55000
5     shahid@gmail.com         70000

In [126]:
# Product wise whole sales
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Product_Name'], as_index = False)['Product_Cost'].sum()

         Product_Name  Product_Cost
0  Kindle Paper White         40000
1  LG Washing Machine         25000
2             Samsung         30000
3            Sofa set         50000
4          hTC mobile         30000
5                iPad         70000
6            iPhone 8         60000
7            iPhone 9         30000

In [127]:
# Day wise product sales
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Date'], as_index = False)['Product_Cost'].sum()

         Date  Product_Cost
0  09/01/2019         70000
1  09/02/2019         25000
2  09/06/2019        100000
3  10/31/2019         10000
4  11/02/2019         35000
5  11/06/2019         80000
6  11/10/2019         15000

In [128]:
# Describe method()
df.describe()

        Order_Id  Customer_Id  Product_Cost
count  15.000000    15.000000     15.000000
mean    8.000000     2.800000  22333.333333
std     4.472136     1.567528  16888.993316
min     1.000000     1.000000  10000.000000
25%     4.500000     1.500000  10000.000000
50%     8.000000     3.000000  20000.000000
75%    11.500000     4.000000  22500.000000
max    15.000000     6.000000  70000.000000

In [129]:
df['Product_Cost'].describe()

count       15.000000
mean     22333.333333
std      16888.993316
min      10000.000000
25%      10000.000000
50%      20000.000000
75%      22500.000000
max      70000.000000
Name: Product_Cost, dtype: float64

Min 25% 50% and 75% Max is called 5 number summary.

Applying a single function to columns in groups

Providing function as a value to the key in dictionary

In [130]:
d = {'Product_Cost':sum}
print(d)

{'Product_Cost': <built-in function sum>}

sum is a predefined aggregation function that can be applied to a column in Pandas.
In this case, we apply the sum() operation on the Product_Cost column after grouping the data.

Instead of directly calling .sum(), we can also use the .agg() method and pass the aggregation function (like 'sum') in a dictionary format, where the key is the column name and the value is the function to apply.

In [131]:
# Now let's calculate the revenue generated as sales on a given day
import pandas as pd
d = {'Product_Cost':sum}
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Date', 'Product_Name']).agg(d)

/tmp/ipykernel_45972/2919058869.py:5: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['Date', 'Product_Name']).agg(d)

                               Product_Cost
Date       Product_Name
09/01/2019 iPad                       70000
09/02/2019 LG Washing Machine         25000
09/06/2019 Kindle Paper White         30000
           Sofa set                   50000
           iPhone 8                   20000
10/31/2019 Kindle Paper White         10000
11/02/2019 Samsung                    20000
           hTC mobile                 15000
11/06/2019 Samsung                    10000
           iPhone 8                   40000
           iPhone 9                   30000
11/10/2019 hTC mobile                 15000

In [133]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Date', 'Product_Name'])['Product_Cost'].sum()

Date        Product_Name
09/01/2019  iPad                  70000
09/02/2019  LG Washing Machine    25000
09/06/2019  Kindle Paper White    30000
            Sofa set              50000
            iPhone 8              20000
10/31/2019  Kindle Paper White    10000
11/02/2019  Samsung               20000
            hTC mobile            15000
11/06/2019  Samsung               10000
            iPhone 8              40000
            iPhone 9              30000
11/10/2019  hTC mobile            15000
Name: Product_Cost, dtype: int64

count is a pandas function and sum is a python function

In [2]:
import pandas as pd
d = {'Product_Cost': sum, 'Product_Name': 'count'}
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Date','Product_Name']).agg(d)

/tmp/ipykernel_606/2277367934.py:4: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['Date','Product_Name']).agg(d)

                               Product_Cost  Product_Name
Date       Product_Name
09/01/2019 iPad                       70000             1
09/02/2019 LG Washing Machine         25000             1
09/06/2019 Kindle Paper White         30000             2
           Sofa set                   50000             1
           iPhone 8                   20000             1
10/31/2019 Kindle Paper White         10000             1
11/02/2019 Samsung                    20000             2
           hTC mobile                 15000             1
11/06/2019 Samsung                    10000             1
           iPhone 8                   40000             2
           iPhone 9                   30000             1
11/10/2019 hTC mobile                 15000             1

.agg() is used to apply one or more aggregation functions on grouped data (or even on a DataFrame/Series).

In [9]:
import pandas as pd
d = {'Product_Cost': ['min', 'max','sum']}
df = pd.read_csv('/content/sample_data/sales5.csv')
df.groupby(['Product_Name','Product_Cost']).agg(d)

                                Product_Cost
                                         min    max    sum
Product_Name       Product_Cost
Kindle Paper White 10000               10000  10000  20000
                   20000               20000  20000  20000
LG Washing Machine 25000               25000  25000  25000
Samsung            10000               10000  10000  30000
Sofa set           50000               50000  50000  50000
hTC mobile         15000               15000  15000  30000
iPad               70000               70000  70000  70000
iPhone 8           20000               20000  20000  60000
iPhone 9           30000               30000  30000  30000

When we know the name of the function but we don’t know the body of the function then we will use pass in this case function implementation we can do later then we can go for pass keyword

As we don’t know the body we should not leave the body empty  as it will throw an indentation error

In [11]:
# Pass Keyword:
def daniel():
  pass
daniel()  # --> output will be blank

In [15]:
# One function calling another
def manoj():
  print('kumar')
  priya()
def priya():
  print('lakshmi')
manoj()

kumar
lakshmi

In [16]:
def manoj():
  print('kumar')
  priya()
def priya():
  print('lakshmi')
  papi()
def papi():
  print('Naidu')
manoj()

kumar
lakshmi
Naidu

In [19]:
# split method
values = ['100$', '200$', '300$']
print(sum(values))

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [20]:
# split method
values = ['100$', '200$', '300$']
print(values.split('$'))

AttributeError: 'list' object has no attribute 'split'

In [21]:
# split method
values = ['100$', '200$', '300$']
for value in values:
  print(value.split('$'))

['100', '']
['200', '']
['300', '']

In [23]:
# split method
values = ['100$', '200$', '300$']
for value in values:
  print(value.split('$')[0])

100
200
300

In [25]:
# split method
values = ['100$', '200$', '300$']
for value in values:
  print(type(value.split('$')[0]))

<class 'str'>
<class 'str'>
<class 'str'>

In [26]:
# split method
values = ['100$', '200$', '300$']
for value in values:
  print(int(value.split('$')[0]))

100
200
300

In [27]:
# split method
values = ['100$', '200$', '300$']
for value in values:
  print(type(int(value.split('$')[0])))

<class 'int'>
<class 'int'>
<class 'int'>

DataFrame Merging or joining

This is same as join operations in database and here we are performing join in between the DataFrames

merge(p1, p2, p3, p4) is a predefined function in pandas.
o pd.merge(df1, df2, on = "column", how = "type of join")

'how'  is a key word argument
The how argument helps to specify the type of join.

Inner Merge / Inner join
We can perform inner join on DataFrames.

This inner join is a kind of intersection means, it keeps the common data.

In [34]:
# inner join
import pandas as pd

d1 = {
    "Id": [1, 2, 3, 4, 5, 6],
    "Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan", "Shafi", "Veeru"],
    "Subject": ["English", "Java", "Html", "Python", "C", "dot net"]
}

d2 = {
    "Id": [11, 12, 13, 14, 15, 16],
    "Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun", "Veeru"],
    "Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
inner_join = pd.merge(df1,df2, on = 'Subject', how = 'inner')
inner_join

   Id_x      Name_x  Subject  Id_y   Name_y
0     2        Venu     Java    11    Srinu
1     3   Madhurima     Html    12  Sumanth
2     4  Nireekshan   Python    14   Daniel
3     5       Shafi        C    15    Arjun
4     6       Veeru  dot net    16    Veeru

In inner join the common data in both the dataframes we will get it as result if no common it will be left out automatically

Left Merge / Left outer join:

Keep every row in the left dataframe.

Where there are missing values of the "on" variable in the right dataframe filled with NaN values in the result.

We will get left side data along with the common data from right side and wherever the record is not matching on the left side data with right side data there we will get NaN

In [36]:
import pandas as pd

d1 = {
    "Id": [1, 2, 3, 4, 5, 6],
    "Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan", "Shafi", "Veeru"],
    "Subject": ["English", "Java", "Html", "Python", "C", "dot net"]
}

d2 = {
    "Id": [11, 12, 13, 14, 15, 16],
    "Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun", "Veeru"],
    "Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
left_join = pd.merge(df1,df2, on = 'Subject',how = 'left')
left_join

   Id_x      Name_x  Subject  Id_y   Name_y
0     1     Pradhan  English   NaN      NaN
1     2        Venu     Java  11.0    Srinu
2     3   Madhurima     Html  12.0  Sumanth
3     4  Nireekshan   Python  14.0   Daniel
4     5       Shafi        C  15.0    Arjun
5     6       Veeru  dot net  16.0    Veeru

In [40]:
# right join is opposite of left join
right_join = pd.merge(df1, df2, on = 'Subject', how = 'right')
right_join

   Id_x      Name_x  Subject  Id_y   Name_y
0   2.0        Venu     Java    11    Srinu
1   3.0   Madhurima     Html    12  Sumanth
2   NaN         NaN      Cpp    13  Neelima
3   4.0  Nireekshan   Python    14   Daniel
4   5.0       Shafi        C    15    Arjun
5   6.0       Veeru  dot net    16    Veeru

Outer Merge / Full outer join:

A full outer join returns all the rows from the left and right DataFrames.

Where there is no common data there it will be filled with NaN values.

In [43]:
outer_join = pd.merge(df1, df2, on = 'Subject', how = 'outer')
outer_join

   Id_x      Name_x  Subject  Id_y   Name_y
0   5.0       Shafi        C  15.0    Arjun
1   NaN         NaN      Cpp  13.0  Neelima
2   1.0     Pradhan  English   NaN      NaN
3   3.0   Madhurima     Html  12.0  Sumanth
4   2.0        Venu     Java  11.0    Srinu
5   4.0  Nireekshan   Python  14.0   Daniel
6   6.0       Veeru  dot net  16.0    Veeru

completely unique keys in both DataFrames

Each row matches exactly once

One row in df1 → matches exactly one row in df2

In [2]:
# one to one
import pandas as pd

b1 = {
    "Employee": ["Nireekshan", "Veeru", "Lavanya", "Pradhan"],
    "Group": ["Development", "Testing", "Testing", "HR"]
}

b2 = {
    "Employee": ["Lavanya", "Nireekshan", "Veeru", "Pradhan"],
    "Hire_date": [2010, 2012, 2014, 2016]
}
df1 = pd.DataFrame(b1)
df2 = pd.DataFrame(b2)
one_one = pd.merge(df1,df2)
one_one

     Employee        Group  Hire_date
0  Nireekshan  Development       2012
1       Veeru      Testing       2014
2     Lavanya      Testing       2010
3     Pradhan           HR       2016

Many-to-one joins occur when the key column has duplicate values in one DataFrame and unique values in the other.

In [16]:
# Many to one
import pandas as pd

b1 = {
    "Employee": ["Nireekshan", "Veeru", "Lavanya", "Pradhan"],
    "Group": ["Development", "Testing", "Testing", "HR"]
}

b2 = {
    "Employee": ["Lavanya", "Nireekshan", "Veeru", "Pradhan"],
    "Hire_date": [2010, 2012, 2014, 2016]
}

b3 = {'Group': ['Testing', 'Development', 'HR'],
      'supervisor':['Shafi', 'Daniel', 'Neelima']
}
df1 = pd.DataFrame(b1)
df2 = pd.DataFrame(b2)
df3 = pd.DataFrame(b3)
# first let's do one_to_one
one_one = pd.merge(df1,df2)
print(one_one)
print()
print()
print(df3)

     Employee        Group  Hire_date
0  Nireekshan  Development       2012
1       Veeru      Testing       2014
2     Lavanya      Testing       2010
3     Pradhan           HR       2016


         Group supervisor
0      Testing      Shafi
1  Development     Daniel
2           HR    Neelima

In [14]:
# Now let's perform many_to one
many_to_one = pd.merge(one_one, df3)
many_to_one

     Employee        Group  Hire_date supervisor
0  Nireekshan  Development       2012     Daniel
1       Veeru      Testing       2014      Shafi
2     Lavanya      Testing       2010      Shafi
3     Pradhan           HR       2016    Neelima

Many-to-many joins occur when the key column has duplicate values in both DataFrames, resulting in multiple combinations of matching rows.

In [15]:
# Many_to_Many
import pandas as pd

d1 = {
    "Employee": ["Nireekshan", "Veeru", "Lavanya", "Pradhan"],
    "Group": ["Development", "Testing", "Testing", "HR"]
}

d2 = {
    "Group": ["Testing", "Testing", "Development", "Development", "HR", "HR"],
    "Skills": ["Manual", "Automation", "Coding", "Logical", "Spreadsheets", "Organization"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
print(df1)
print()
print(df2)
many_to_many = pd.merge(df1,df2)
many_to_many

     Employee        Group
0  Nireekshan  Development
1       Veeru      Testing
2     Lavanya      Testing
3     Pradhan           HR

         Group        Skills
0      Testing        Manual
1      Testing    Automation
2  Development        Coding
3  Development       Logical
4           HR  Spreadsheets
5           HR  Organization

     Employee        Group        Skills
0  Nireekshan  Development        Coding
1  Nireekshan  Development       Logical
2       Veeru      Testing        Manual
3       Veeru      Testing    Automation
4     Lavanya      Testing        Manual
5     Lavanya      Testing    Automation
6     Pradhan           HR  Spreadsheets
7     Pradhan           HR  Organization

In [18]:
# Column wise merging of the DataFrames
import pandas as pd

d1 = {
    "Id": [1, 2, 3, 4, 5, 6],
    "Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan", "Shafi", "Veeru"],
    "Subject": ["English", "Java", "Html", "Python", "C", "dot net"]
}

d2 = {
    "Id": [11, 12, 13, 14, 15, 16],
    "Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun", "Veeru"],
    "Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
}
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)
print(df1)
print()
print(df2)

   Id        Name  Subject
0   1     Pradhan  English
1   2        Venu     Java
2   3   Madhurima     Html
3   4  Nireekshan   Python
4   5       Shafi        C
5   6       Veeru  dot net

   Id     Name  Subject
0  11    Srinu     Java
1  12  Sumanth     Html
2  13  Neelima      Cpp
3  14   Daniel   Python
4  15    Arjun        C
5  16    Veeru  dot net

In [21]:
# Merging 2 dataframes based on a single column
# In this common data is displayed and unique data is ignored
result = pd.merge(df1,df2, on = 'Subject')
result

   Id_x      Name_x  Subject  Id_y   Name_y
0     2        Venu     Java    11    Srinu
1     3   Madhurima     Html    12  Sumanth
2     4  Nireekshan   Python    14   Daniel
3     5       Shafi        C    15    Arjun
4     6       Veeru  dot net    16    Veeru

In [22]:
# Merging two DataFrames with multiple columns
# we will see results only if there is common data on both the columns
result = pd.merge(df1,df2, on = ['Name','Subject'])
result
# we only have one row with common data that matches both the columns

   Id_x   Name  Subject  Id_y
0     6  Veeru  dot net    16

Concat(p): It is a predefined function

This function concatinates one DataFrame to another DataFrame

List data structure is capable of even storing a DataFrame Object

In [26]:
import pandas as pd
d1 = [[11, 22],[33, 44]]
d2 = [[55, 66], [77, 88]]
c1 = ['A', 'B']
df1 = pd.DataFrame(d1, columns = c1)
df2 = pd.DataFrame(d2, columns = c1)
print(df1)
print()
print(df2)

    A   B
0  11  22
1  33  44

    A   B
0  55  66
1  77  88

In [29]:
# Concatenating one DataFrame with another DataFrame
result = pd.concat([df1,df2])
print(result)

    A   B
0  11  22
1  33  44
0  55  66
1  77  88

To get the index right we have a keyword argument called ignore_index = True

In [30]:
result = pd.concat([df1,df2], ignore_index = True)
print(result)

    A   B
0  11  22
1  33  44
2  55  66
3  77  88

In [33]:
import pandas as pd
d1 = [[11, 22],[33, 44]]
d2 = [[55, 66], [77, 88]]
c1 = ['A', 'B']
c2 = ['X','Y']
df1 = pd.DataFrame(d1, columns = c1)
df2 = pd.DataFrame(d2, columns = c2)
print(df1)
print()
print(df2)
result = pd.concat([df1,df2])
result

    A   B
0  11  22
1  33  44

    X   Y
0  55  66
1  77  88

      A     B     X     Y
0  11.0  22.0   NaN   NaN
1  33.0  44.0   NaN   NaN
0   NaN   NaN  55.0  66.0
1   NaN   NaN  77.0  88.0

Here when we use axis = 0 which refers to rows and operations are performed along vertical axis
By default axis = 0

when we use axis = 1 which refers to columns and operations are performed along horizontal axis

In [34]:
result = pd.concat([df1,df2],axis = 1)
result

    A   B   X   Y
0  11  22  55  66
1  33  44  77  88

so:

axis=0: Operates along rows (column-wise operation).

axis=1: Operates along columns (row-wise operation).

In [35]:
# Summing along axis=0 (column-wise sum)
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]})
column_sum = df.sum(axis = 0)
print(column_sum)

A     6
B    15
C    24
dtype: int64

In [36]:
# Summing along axis=1 (column-wise sum)
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]})
column_sum = df.sum(axis = 1)
print(column_sum)

0    12
1    15
2    18
dtype: int64

DataFrame - Adding, dropping columns & rows

In [37]:
df = pd.read_csv('/content/sample_data/sales8.csv')
df.head()

,Order Id,Customer name,Customer Id,Product name,Product cost,Quantity
0,192837,Veeru,3,LG Mobile,65999,1
1,192838,Neelima,19,Apple iPad 10.2-inch,63000,2
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1
3,192840,Shahid,20,iPhone 11,60000,2
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3

In [38]:
df['Total_value'] = df['Product cost'] * df['Quantity']
df.head()

,Order Id,Customer name,Customer Id,Product name,Product cost,Quantity,Total_value
0,192837,Veeru,3,LG Mobile,65999,1,65999
1,192838,Neelima,19,Apple iPad 10.2-inch,63000,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1,75999
3,192840,Shahid,20,iPhone 11,60000,2,120000
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3,209997

We can even use a method called apply() to perform the above action

In [39]:
# Apply method we are not using it in real time
import pandas as pd
df = pd.read_csv('/content/sample_data/sales8.csv')
def Manoj(df):
  t = df['Product cost'] * df['Quantity']
  return t
df['Total cost'] = df.apply(Manoj,axis = 1)
df.head()

,Order Id,Customer name,Customer Id,Product name,Product cost,Quantity,Total cost
0,192837,Veeru,3,LG Mobile,65999,1,65999
1,192838,Neelima,19,Apple iPad 10.2-inch,63000,2,126000
2,192839,Balaji,12,34in Ultrawide Monitor,75999,1,75999
3,192840,Shahid,20,iPhone 11,60000,2,120000
4,192841,Vinay,10,Bose SoundSport Headphones,69999,3,209997

Generally column adds at the end of the dataframe

so now to add a column at a specific position we have a method called insert()

Insert() method takes 3 parameters

1st which position you want your column

2nd the column name

3rd the operation

In [40]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales8.csv')
df.insert(4, 'Total_value', df['Product cost'] * df['Quantity'])
df.head()
# df.insert(position, column name, operation)

,Order Id,Customer name,Customer Id,Product name,Total_value,Product cost,Quantity
0,192837,Veeru,3,LG Mobile,65999,65999,1
1,192838,Neelima,19,Apple iPad 10.2-inch,126000,63000,2
2,192839,Balaji,12,34in Ultrawide Monitor,75999,75999,1
3,192840,Shahid,20,iPhone 11,120000,60000,2
4,192841,Vinay,10,Bose SoundSport Headphones,209997,69999,3

In [42]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales8.csv')
df.insert(1, 'Total_value', df['Product cost']* df['Quantity'])
df.head()

,Order Id,Total_value,Customer name,Customer Id,Product name,Product cost,Quantity
0,192837,65999,Veeru,3,LG Mobile,65999,1
1,192838,126000,Neelima,19,Apple iPad 10.2-inch,63000,2
2,192839,75999,Balaji,12,34in Ultrawide Monitor,75999,1
3,192840,120000,Shahid,20,iPhone 11,60000,2
4,192841,209997,Vinay,10,Bose SoundSport Headphones,69999,3

In [46]:
# Dropping columns form the dataframe
import pandas as pd
df = pd.read_csv('/content/sample_data/sales8.csv')
df = df.drop(columns = 'Quantity')
df.head()
# drop method creates a new dataframe and doesn't modify the original dataframe
# we can even use inplace = True

,Order Id,Customer name,Customer Id,Product name,Product cost
0,192837,Veeru,3,LG Mobile,65999
1,192838,Neelima,19,Apple iPad 10.2-inch,63000
2,192839,Balaji,12,34in Ultrawide Monitor,75999
3,192840,Shahid,20,iPhone 11,60000
4,192841,Vinay,10,Bose SoundSport Headphones,69999

To make sure that the operation is being applied column wise we can use axis =1

In [47]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales8.csv')
df.drop(columns = ['Quantity','Product cost'], axis = 1, inplace = True)
df.head()

   Order Id Customer name  Customer Id                Product name
0    192837         Veeru            3                   LG Mobile
1    192838       Neelima           19        Apple iPad 10.2-inch
2    192839        Balaji           12      34in Ultrawide Monitor
3    192840        Shahid           20                   iPhone 11
4    192841         Vinay           10  Bose SoundSport Headphones

To save the DataFrame to csv file we have a method called to_csv()

In [22]:
# Dropping rows from DataFrame --> Not used in real time
import pandas as pd
df = pd.read_csv('/content/sample_data/sales8.csv')
print(df.head())

print()

df.drop([0,1,2], inplace = True, axis = 0)
print(df.head())

   Order Id Customer name  Customer Id                Product name  \
0    192837         Veeru            3                   LG Mobile
1    192838       Neelima           19        Apple iPad 10.2-inch
2    192839        Balaji           12      34in Ultrawide Monitor
3    192840        Shahid           20                   iPhone 11
4    192841         Vinay           10  Bose SoundSport Headphones

   Product cost  Quantity
0         65999         1
1         63000         2
2         75999         1
3         60000         2
4         69999         3

   Order Id Customer name  Customer Id                Product name  \
3    192840        Shahid           20                   iPhone 11
4    192841         Vinay           10  Bose SoundSport Headphones
5    192842         Vinay           10                20in Monitor
6    192843        Balaji           12                    iPhone 8
7    192844    Nireekshan            1      27in 4K Gaming Monitor

   Product cost  Quantity
3         60000         2
4         69999         3
5         65999         2
6         55999         3
7         55999         3

DataFrame Date and time

a = 30-10-2023 date type data type

Based on the requirement we can capture only day value or month value or year value.

Ex time stamp:
a = 30-10-2023 07:30:00

07 --> hours, 30 --> mins and 00 --> sec

if a column contains date values by default pandas will consider that column as object data type.

Now to consider the datetime data type as it is instead of object data type we will use parse_dates = ['name of the column1', 'name of the column2']

In [26]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales7_dates.csv')
df.head()
df.dtypes

Order_Id          int64
Customer_Name    object
Customer_Id       int64
Product_Name     object
Product_Cost      int64
Pur_Date         object
dtype: object

parse_dates --> Only booleans, lists, and dictionaries are accepted for the 'parse_dates' as parameter. so we have given ''Pur_Date'' in empty list

In [28]:
# Now let's convert the pur_date column into date type data type from string data type
df = pd.read_csv('/content/sample_data/sales7_dates.csv', parse_dates = ['Pur_Date'])
df.dtypes

Order_Id                  int64
Customer_Name            object
Customer_Id               int64
Product_Name             object
Product_Cost              int64
Pur_Date         datetime64[ns]
dtype: object

if we do not convert we can perform only string operation

But performing string operations on datetype data type does not make any sense. so we will convert.

How to convert?
case 1 --> While loading the file
case 2 --> after loading the file

We already covered case1 in the above example now let's understand case 2

We can convert from object data type into datetime data type explicitly.


By using,
--> to_datetime(p) function --> important

--> astype(p) method in Series --> not so important

In [34]:
# to_datetime function
import pandas as pd
df= pd.read_csv('/content/sample_data/sales7_dates.csv')
print(df.head())

print()

df.dtypes

   Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1023         Venki           15            27in FHD Monitor
1      1024    Chaithanya           14                   iPhone 11
2      1025        Shahid           20  Bose SoundSport Headphones
3      1026         Veeru            3        Apple iPad 10.2-inch
4      1027          Venu           23                Google Phone

   Product_Cost       Pur_Date
0         59000  1/1/2019 0:00
1         69000  1/1/2019 1:00
2         65999  1/1/2019 2:00
3         63999  1/1/2019 3:00
4         63999  1/1/2019 4:00

Order_Id          int64
Customer_Name    object
Customer_Id       int64
Product_Name     object
Product_Cost      int64
Pur_Date         object
dtype: object

In [35]:
df['Pur_Date'] = pd.to_datetime(df['Pur_Date'])
df.head()
print()
df.dtypes

Order_Id                  int64
Customer_Name            object
Customer_Id               int64
Product_Name             object
Product_Cost              int64
Pur_Date         datetime64[ns]
dtype: object

astype() method in Series class
we can use this method only on series

syntax: df['Pur_Date'].astype('datetime64[ns]')

In [36]:
import pandas as pdd
df = pd.read_csv('/content/sample_data/sales7_dates.csv')
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date
0,1023,Venki,15,27in FHD Monitor,59000,1/1/2019 0:00
1,1024,Chaithanya,14,iPhone 11,69000,1/1/2019 1:00
2,1025,Shahid,20,Bose SoundSport Headphones,65999,1/1/2019 2:00
3,1026,Veeru,3,Apple iPad 10.2-inch,63999,1/1/2019 3:00
4,1027,Venu,23,Google Phone,63999,1/1/2019 4:00

In [38]:
df.dtypes

Order_Id          int64
Customer_Name    object
Customer_Id       int64
Product_Name     object
Product_Cost      int64
Pur_Date         object
dtype: object

In [40]:
df = pd.read_csv('/content/sample_data/sales7_dates.csv')
df['Pur_Date'] = df['Pur_Date'].astype('datetime64[ns]')
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date
0,1023,Venki,15,27in FHD Monitor,59000,2019-01-01 00:00:00
1,1024,Chaithanya,14,iPhone 11,69000,2019-01-01 01:00:00
2,1025,Shahid,20,Bose SoundSport Headphones,65999,2019-01-01 02:00:00
3,1026,Veeru,3,Apple iPad 10.2-inch,63999,2019-01-01 03:00:00
4,1027,Venu,23,Google Phone,63999,2019-01-01 04:00:00

In [42]:
df.dtypes

Order_Id                  int64
Customer_Name            object
Customer_Id               int64
Product_Name             object
Product_Cost              int64
Pur_Date         datetime64[ns]
dtype: object

In [43]:
import pandas as pd

data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['20190902', '20190913', '20190921'],
}

df = pd.DataFrame(data)
df

df.dtypes

Product    object
Status     object
Cost        int64
PurDate    object
dtype: object

In [46]:
# Now let's convert the PurDate to datetime datatype
df['PurDate'] = pd.to_datetime(df['PurDate'])
df.head()
print()
df.dtypes

Product            object
Status             object
Cost                int64
PurDate    datetime64[ns]
dtype: object

In [49]:
import pandas as pd
data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['02012019', '13092019', '21092019'],
}
df = pd.DataFrame(data)
df

    Product   Status   Cost   PurDate
0   Samsung  Success  10000  02012019
1    iPhone  Success  50000  13092019
2  Motorola   Failed  15000  21092019

In [51]:
df['PurDate'] = pd.to_datetime(df['PurDate'], format = '%d%m%Y')
df.head()

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-01-02
1    iPhone  Success  50000 2019-09-13
2  Motorola   Failed  15000 2019-09-21

Pandas by default it will print : yyyy-mm-dd

In [54]:
import pandas as pd
data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['02Sep2019', '13sep2019', '21Sep2019'],
}
df = pd.DataFrame(data)
df

    Product   Status   Cost    PurDate
0   Samsung  Success  10000  02Sep2019
1    iPhone  Success  50000  13sep2019
2  Motorola   Failed  15000  21Sep2019

In [55]:
df['PurDate'] = pd.to_datetime(df['PurDate'])
df

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-09-02
1    iPhone  Success  50000 2019-09-13
2  Motorola   Failed  15000 2019-09-21

If we provid the format pandas avoids guess work

In [56]:
df['PurDate'] = pd.to_datetime(df['PurDate'], format = '%d%b%Y')
df

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-09-02
1    iPhone  Success  50000 2019-09-13
2  Motorola   Failed  15000 2019-09-21

In [57]:
import pandas as pd
data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['02-Sep-2019', '13-sep-2019', '21-Sep-2019'],
}
df = pd.DataFrame(data)
df

    Product   Status   Cost      PurDate
0   Samsung  Success  10000  02-Sep-2019
1    iPhone  Success  50000  13-sep-2019
2  Motorola   Failed  15000  21-Sep-2019

In [58]:
df['PurDate'] = pd.to_datetime(df['PurDate'])
df

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-09-02
1    iPhone  Success  50000 2019-09-13
2  Motorola   Failed  15000 2019-09-21

In [59]:
import pandas as pd
data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['20190902093000', '20190913093000', '20190921200000'],
}
df = pd.DataFrame(data)
df

    Product   Status   Cost         PurDate
0   Samsung  Success  10000  20190902093000
1    iPhone  Success  50000  20190913093000
2  Motorola   Failed  15000  20190921200000

In [60]:
df['PurDate'] = pd.to_datetime(df['PurDate'])
df

    Product   Status   Cost             PurDate
0   Samsung  Success  10000 2019-09-02 09:30:00
1    iPhone  Success  50000 2019-09-13 09:30:00
2  Motorola   Failed  15000 2019-09-21 20:00:00

Nat values

errors = "coerce"

converting indian time stamp to usa time stamp

When we are trying to convert the date column we should ensure that the data in the date column should have datetime format or else we will get an error.

In [61]:
import pandas as pd
data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['02-Sep-2019', 'Missing date', '21-Sep-2019'],
}
df = pd.DataFrame(data)
df

    Product   Status   Cost       PurDate
0   Samsung  Success  10000   02-Sep-2019
1    iPhone  Success  50000  Missing date
2  Motorola   Failed  15000   21-Sep-2019

Errors that belong to the same category but have different messages are called exceptions of the same type.

ValueError: invalid literal for int() with base 10: 'abc'

ValueError: math domain error

In [62]:
# Now let's try to convert the PurDate column into datetime data type
df['PurDate'] = pd.to_datetime(df['PurDate'])
df

ValueError: time data "Missing date" doesn't match format "%d-%b-%Y", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

errors = "coerce" keyword argument converts Date column missing values into NaT (Not a Time) values.

errors='coerce' converts unparseable (invalid) date values into NaT (Not a Time).

In [64]:
df['PurDate'] = pd.to_datetime(df['PurDate'], errors = 'coerce')
df

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2019-09-02
1    iPhone  Success  50000        NaT
2  Motorola   Failed  15000 2019-09-21

Based on requirement we can select specific dates, like:

Start date to end date

In [66]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales7_dates.csv', parse_dates = ['Pur_Date'])
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date
0,1023,Venki,15,27in FHD Monitor,59000,2019-01-01 00:00:00
1,1024,Chaithanya,14,iPhone 11,69000,2019-01-01 01:00:00
2,1025,Shahid,20,Bose SoundSport Headphones,65999,2019-01-01 02:00:00
3,1026,Veeru,3,Apple iPad 10.2-inch,63999,2019-01-01 03:00:00
4,1027,Venu,23,Google Phone,63999,2019-01-01 04:00:00

In [67]:
df.dtypes

Order_Id                  int64
Customer_Name            object
Customer_Id               int64
Product_Name             object
Product_Cost              int64
Pur_Date         datetime64[ns]
dtype: object

In [70]:
a = df['Pur_Date'] >= '2019-01-01 00:00:00'
b = df['Pur_Date'] < '2019-01-01 05:00:00'
df[a & b]

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date
0,1023,Venki,15,27in FHD Monitor,59000,2019-01-01 00:00:00
1,1024,Chaithanya,14,iPhone 11,69000,2019-01-01 01:00:00
2,1025,Shahid,20,Bose SoundSport Headphones,65999,2019-01-01 02:00:00
3,1026,Veeru,3,Apple iPad 10.2-inch,63999,2019-01-01 03:00:00
4,1027,Venu,23,Google Phone,63999,2019-01-01 04:00:00

Based on requirement we can get last 10 days, 20 days, 40 days, 1
month, 2 months, 3 months, 1 year and 2 years date data as well.

We can also sort the dataframe by using sort_values()

To access specific dates we have a method called set_index()

In [72]:
# Access specific dates like last 20 days or 2 months or 2 years records
# 1st let's set Pur_Date column as index
# once we do this as index is not countable we will have only 5 columns
import pandas as pd
df = pd.read_csv('/content/sample_data/sales7_dates.csv', parse_dates =['Pur_Date'])
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date
0,1023,Venki,15,27in FHD Monitor,59000,2019-01-01 00:00:00
1,1024,Chaithanya,14,iPhone 11,69000,2019-01-01 01:00:00
2,1025,Shahid,20,Bose SoundSport Headphones,65999,2019-01-01 02:00:00
3,1026,Veeru,3,Apple iPad 10.2-inch,63999,2019-01-01 03:00:00
4,1027,Venu,23,Google Phone,63999,2019-01-01 04:00:00

In [75]:
# 1st let's set Pur_Date column as index using set_index method
df = df.set_index('Pur_Date')
df.head()

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
Pur_Date,,,,,
2019-01-01 00:00:00,1023,Venki,15,27in FHD Monitor,59000
2019-01-01 01:00:00,1024,Chaithanya,14,iPhone 11,69000
2019-01-01 02:00:00,1025,Shahid,20,Bose SoundSport Headphones,65999
2019-01-01 03:00:00,1026,Veeru,3,Apple iPad 10.2-inch,63999
2019-01-01 04:00:00,1027,Venu,23,Google Phone,63999

In [76]:
# let's access last 10 days records
last_10days = df.last('10D')
last_10days

/tmp/ipykernel_1812/2183395706.py:2: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  last_10days = df.last('10D')

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost
Pur_Date,,,,,
2020-02-11 15:00:00,10782,Harsha,5,Google Phone,75000
2020-02-11 16:00:00,10783,Veeru,3,Google Phone,61000
2020-02-11 17:00:00,10784,Vinay,10,34in Ultrawide Monitor,69999
2020-02-11 18:00:00,10785,Jaya Chandra,21,ThinkPad Laptop,50000
2020-02-11 19:00:00,10786,Shahid,20,iPhone 11,51999
...,...,...,...,...,...
2020-02-21 10:00:00,11017,Karteek,4,20in Monitor,51999
2020-02-21 11:00:00,11018,Vinay,10,Apple Airpods Headphones,75999
2020-02-21 12:00:00,11019,Neelima,19,LG ThinQ Refrigerator,75999
2020-02-21 13:00:00,11020,Siddhu,18,iPhone 7s,65999
2020-02-21 14:00:00,11021,Tarun,11,34in Ultrawide Monitor,55000

Extract year, month, day from Date column

Based on requirement we can get year, month, day, hour, minute from
Date column.

Sometimes it can be useful to break up a column of dates into
components.

In [78]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sales7_dates.csv', parse_dates = ['Pur_Date'])
df.head(2)

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date
0,1023,Venki,15,27in FHD Monitor,59000,2019-01-01 00:00:00
1,1024,Chaithanya,14,iPhone 11,69000,2019-01-01 01:00:00

In [79]:
df['Pur_Date'].head(4)

0   2019-01-01 00:00:00
1   2019-01-01 01:00:00
2   2019-01-01 02:00:00
3   2019-01-01 03:00:00
Name: Pur_Date, dtype: datetime64[ns]

Now let's access only year

syntax: df['column'].dt.year

.dt is an attribute inside Series class like . index , .value

In [81]:
df['Pur_Date'].dt.year.head(2)

0    2019
1    2019
Name: Pur_Date, dtype: int32

In [82]:
df['Pur_Date'].dt.month.head(2)

0    1
1    1
Name: Pur_Date, dtype: int32

In [83]:
# Let's add teh year column to the currenyt dataframe
df['Year'] = df['Pur_Date'].dt.year
df.head(2)

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Pur_Date,Year
0,1023,Venki,15,27in FHD Monitor,59000,2019-01-01 00:00:00,2019
1,1024,Chaithanya,14,iPhone 11,69000,2019-01-01 01:00:00,2019

In [85]:
# Encoding Days of the Week
df['Pur_Date'].dt.day_name().head()

0    Tuesday
1    Tuesday
2    Tuesday
3    Tuesday
4    Tuesday
Name: Pur_Date, dtype: object

In [87]:
import pandas as pd

data = {
    'Product': ['Samsung', 'iPhone', 'Motorola'],
    'Status': ['Success', 'Success', 'Failed'],
    'Cost': [10000, 50000, 15000],
    'PurDate': ['2018-01-01', '2018-01-02', '2018-01-03'],
}

df = pd.DataFrame(data)
df['PurDate'] = pd.to_datetime(df['PurDate'])
df.head()

    Product   Status   Cost    PurDate
0   Samsung  Success  10000 2018-01-01
1    iPhone  Success  50000 2018-01-02
2  Motorola   Failed  15000 2018-01-03

In [88]:
df['PurDate'].dt.day_name()

0       Monday
1      Tuesday
2    Wednesday
Name: PurDate, dtype: object

The day of the week with Monday = 0, .... Sunday = 6

In [89]:
df['PurDate'].dt.weekday

0    0
1    1
2    2
Name: PurDate, dtype: int32

In [90]:
df['PurDate'].dt.weekday + 1

0    1
1    2
2    3
Name: PurDate, dtype: int32

Concatenate Multiple csv files

To load all files from a folder we have os module whcih contains a function listdir --> which means from the directory list all the file names.

next we have to create a string wrt foldername

ex: './folder name' --> . indicates that the folder is existing in the current directory

Next assign a variable to the string --> a = './folder name'

final syntax: all_files = listdir(a)

Next step after accessing all the files we have to filter the files based on the categories.

In sting we have a method called endswith and it returns only boolian data type as result

In [2]:
a = ["Naresh","Suresh","Daniel","Phani","Rajesh","Ramesh"]
# results = [p1,p2,p3]
# results = [variable, for loop, condition]
result = [names for names in a if names.endswith('sh')]
result

['Naresh', 'Suresh', 'Rajesh', 'Ramesh']

Now we can even use filter concept for the above result

In [4]:
a = ["Naresh","Suresh","Daniel","Phani","Rajesh","Ramesh"]
# f = filter(p1,p2)
# f = filter(lambda function, always existing list data structure)
f = filter(lambda names: names.endswith('sh'), a)
f
# Output is filter object

In [5]:
# Now let's convert into list data structure
b = list(f)
b

['Naresh', 'Suresh', 'Rajesh', 'Ramesh']

listdir is a predefined function in os module

This function returns all the file names in the lsit

filter(p1, p2) is a predefined function in python and using filter function we can apply Boolean logic and get results.

Concatenating all csv file

Once after loading all csv files using pandas we can concatenate all csv files into one csv file

all_files = os.path.join(always the folder name that we have created , provide the extension of the file that you are intending to filter)

In [11]:
import os
import glob
a = '/content/sample_data/daniel'
all_files = os.path.join(a, '*.csv')
# we have glob function in glob module.
# It takes a single parameter and gets all files with fully qualified path
# fully qualified path  file names along with their location
alll_files = glob.glob(all_files)
alll_files

['/content/sample_data/daniel/oct_sales.csv',
 '/content/sample_data/daniel/aug_sales.csv',
 '/content/sample_data/daniel/nov_sales.csv',
 '/content/sample_data/daniel/apr_sales.csv',
 '/content/sample_data/daniel/jun_sales.csv',
 '/content/sample_data/daniel/jan_sales.csv',
 '/content/sample_data/daniel/jul_sales.csv',
 '/content/sample_data/daniel/dec_sales.csv',
 '/content/sample_data/daniel/may_sales.csv',
 '/content/sample_data/daniel/feb_sales.csv',
 '/content/sample_data/daniel/mar_sales.csv']

In [12]:
# Now let's print all the files one by one
for files in alll_files:
  print(files)

/content/sample_data/daniel/oct_sales.csv
/content/sample_data/daniel/aug_sales.csv
/content/sample_data/daniel/nov_sales.csv
/content/sample_data/daniel/apr_sales.csv
/content/sample_data/daniel/jun_sales.csv
/content/sample_data/daniel/jan_sales.csv
/content/sample_data/daniel/jul_sales.csv
/content/sample_data/daniel/dec_sales.csv
/content/sample_data/daniel/may_sales.csv
/content/sample_data/daniel/feb_sales.csv
/content/sample_data/daniel/mar_sales.csv

Now let's create a dataframe using the files

We have to make sure that df=pd.read_csv(files) is within the loop orelse only the last file in the loop will get executed leaving other files

All 12 files will be printed

In [15]:
import pandas as pd
for files in alll_files:
  print(files)
  df=pd.read_csv(files)
  print(df)

/content/sample_data/daniel/oct_sales.csv
   Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1914       Karteek            4        27in FHD Monitor         65000
1      1915    Nireekshan            1                iPhone 9         65000
2      1916     Madhurima            7        27in FHD Monitor         65999
3      1917        Balaji           12               iPhone 11         59000
4      1918        Partha            8  34in Ultrawide Monitor         61000
5      1919        Shahid           20                iPhone 8         65999
6      1920       Sumanth           22               LG Mobile         69000
7      1921       Lavanya           16  LG ThinQ Refrigerator          63000
8      1922   Mallikarjun           13  34in Ultrawide Monitor         50000

               Date
0    10/7/2019 3:00
1    10/7/2019 4:00
2    10/8/2019 5:00
3    10/8/2019 6:00
4    10/9/2019 7:00
5    10/9/2019 8:00
6   10/11/2019 9:00
7  10/11/2019 10:00
8  10/12/2019 11:00
/content/sample_data/daniel/aug_sales.csv
   Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1716       Karteek            4                iPhone 8         60000
1      1717  Jaya Chandra           21           Flatscreen TV         63000
2      1718       Sumanth           22               LG Mobile         51999
3      1719        Siddhu           18               iPhone 11         59000
4      1720         Kedar            2  34in Ultrawide Monitor         55000
5      1721       Sumanth           22               LG Mobile         75000
6      1722         Vijay            9      Macbook Pro Laptop         50000
7      1723         Vijay            9           Flatscreen TV         51999
8      1724         Kedar            2               LG Mobile         65000

              Date
0  8/20/2019 21:00
1  8/20/2019 22:00
2  8/21/2019 23:00
3   8/30/2019 0:00
4   8/30/2019 1:00
5   8/30/2019 2:00
6   8/30/2019 3:00
7   8/30/2019 4:00
8   8/30/2019 5:00
/content/sample_data/daniel/nov_sales.csv
   Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      2013        Daniel            6            Google Phone         63999
1      2014       Karteek            4  27in 4K Gaming Monitor         55999
2      2015        Siddhu           18  Samsung Galaxy S9 Plus         50000
3      2016        Partha            8            Google Phone         50000
4      2017         Kedar            2         ThinkPad Laptop         65000
5      2018        Daniel            6        27in FHD Monitor         75000
6      2019        Harsha            5  34in Ultrawide Monitor         55000
7      2020        Balaji           12               LG Mobile         50000
8      2021        Shahid           20                iPhone 9         55999

              Date
0   11/1/2019 6:00
1   11/1/2019 7:00
2   11/2/2019 8:00
3   11/2/2019 9:00
4  11/2/2019 10:00
5  11/2/2019 11:00
6  11/2/2019 12:00
7  11/2/2019 13:00
8  11/2/2019 14:00
/content/sample_data/daniel/apr_sales.csv
   Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1320          Venu           23      LG ThinQ Refrigerator
1      1321  Jaya Chandra           21  Bose SoundSport Headphones
2      1322   Mallikarjun           13    Apple Airpods Headphones
3      1323        Siddhu           18      Samsung Galaxy S9 Plus
4      1324        Daniel            6                    iPhone 8
5      1325        Harsha            5                   LG Mobile
6      1326        Siddhu           18                   iPhone 7s
7      1327         Shafi           25        Apple iPad 10.2-inch
8      1328   Mallikarjun           13            27in FHD Monitor

   Product_Cost             Date
0         55000   4/11/2019 9:00
1         63000  4/13/2019 10:00
2         69999  4/13/2019 11:00
3         55000  4/14/2019 12:00
4         55000  4/15/2019 13:00
5         50000  4/15/2019 14:00
6         69999  4/16/2019 15:00
7         50000  4/16/2019 16:00
8         63999  4/16/2019 17:00
/content/sample_data/daniel/jun_sales.csv
   Order_Id Customer_Name  Customer_Id              Product_Name  \
0      1518    Chaithanya           14        LG Washing Machine
1      1519         Shafi           25                 iPhone 7s
2      1520       Neelima           19              Google Phone
3      1521         Tarun           11  Apple Airpods Headphones
4      1522   Mallikarjun           13          27in FHD Monitor
5      1523        Siddhu           18                 iPhone 7s
6      1524    Nireekshan            1             Flatscreen TV
7      1525        Harsha            5                 LG Mobile
8      1526          Venu           23        Samsung Galaxy S20

   Product_Cost             Date
0         59000   6/1/2019 15:00
1         55999   6/1/2019 16:00
2         65999   6/2/2019 17:00
3         59000   6/2/2019 18:00
4         75999   6/3/2019 19:00
5         55999  6/26/2019 20:00
6         63000  6/26/2019 21:00
7         59000  6/26/2019 22:00
8         55000  6/26/2019 23:00
/content/sample_data/daniel/jan_sales.csv
   Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1023         Venki           15            27in FHD Monitor
1      1024    Chaithanya           14                   iPhone 11
2      1025        Shahid           20  Bose SoundSport Headphones
3      1026         Veeru            3        Apple iPad 10.2-inch
4      1027          Venu           23                Google Phone
5      1028        Daniel            6      Samsung Galaxy S9 Plus
6      1029          Venu           23                   iPhone 11
7      1030         Shafi           25            27in FHD Monitor
8      1031         Kedar            2                20in Monitor

   Product_Cost           Date
0         59000  1/1/2019 0:00
1         69000  1/1/2019 1:00
2         65999  1/2/2019 2:00
3         63999  1/2/2019 3:00
4         63999  1/2/2019 4:00
5         63999  1/2/2019 5:00
6         61000  1/3/2019 6:00
7         63000  1/3/2019 7:00
8         55999  1/3/2019 8:00
/content/sample_data/daniel/jul_sales.csv
   Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1617        Siddhu           18      Samsung Galaxy S20         63999
1      1618       Pradhan           17         ThinkPad Laptop         60000
2      1619   Mallikarjun           13               iPhone 11         55999
3      1620    Nireekshan            1        27in FHD Monitor         75000
4      1621        Daniel            6                iPhone 9         50000
5      1622        Partha            8                iPhone 9         65000
6      1623         Veeru            3                iPhone 9         69999
7      1624         Venki           15                iPhone 8         55000
8      1625       Sumanth           22  Samsung Galaxy S9 Plus         75000

              Date
0  7/25/2019 18:00
1  7/25/2019 19:00
2  7/25/2019 20:00
3  7/25/2019 21:00
4  7/25/2019 22:00
5  7/25/2019 23:00
6   7/26/2019 0:00
7   7/26/2019 1:00
8   7/26/2019 2:00
/content/sample_data/daniel/dec_sales.csv
   Order_Id Customer_Name  Customer_Id              Product_Name  \
0      2112         Mohan           24                  iPhone 8
1      2113    Chaithanya           14  Apple Airpods Headphones
2      2114       Lavanya           16        Macbook Pro Laptop
3      2115        Shahid           20        LG Washing Machine
4      2116         Vinay           10                 LG Mobile
5      2117        Shahid           20      Apple iPad 10.2-inch
6      2118        Shahid           20                  iPhone 9
7      2119    Chaithanya           14             Flatscreen TV
8      2120       Neelima           19    34in Ultrawide Monitor

   Product_Cost              Date
0         50000   12/15/2019 9:00
1         50000  12/15/2019 10:00
2         61000  12/15/2019 11:00
3         55999  12/16/2019 12:00
4         75999  12/16/2019 13:00
5         61000  12/17/2019 14:00
6         63999  12/18/2019 15:00
7         69999  12/19/2019 16:00
8         51999  12/19/2019 17:00
/content/sample_data/daniel/may_sales.csv
   Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1419    Nireekshan            1                20in Monitor
1      1420         Veeru            3             ThinkPad Laptop
2      1421   Mallikarjun           13               Flatscreen TV
3      1422         Shafi           25                   iPhone 11
4      1423        Partha            8          Samsung Galaxy S20
5      1424       Karteek            4                Google Phone
6      1425        Siddhu           18          Macbook Pro Laptop
7      1426         Shafi           25          Macbook Pro Laptop
8      1427       Karteek            4  Bose SoundSport Headphones

   Product_Cost             Date
0         55000  5/17/2019 12:00
1         55000  5/17/2019 13:00
2         55000  5/18/2019 14:00
3         65000  5/18/2019 15:00
4         55000  5/19/2019 16:00
5         63999  5/19/2019 17:00
6         50000  5/20/2019 18:00
7         65000  5/21/2019 19:00
8         65000  5/22/2019 20:00
/content/sample_data/daniel/feb_sales.csv
   Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1122     Madhurima            7               iPhone 11         63000
1      1123        Balaji           12            Google Phone         65999
2      1124  Jaya Chandra           21      LG Washing Machine         75999
3      1125         Vinay           10        27in FHD Monitor         69000
4      1126  Jaya Chandra           21                iPhone 8         63999
5      1127          Venu           23                iPhone 9         51999
6      1128       Sumanth           22  Samsung Galaxy S9 Plus         55000
7      1129       Karteek            4  27in 4K Gaming Monitor         63999
8      1130  Jaya Chandra           21           Flatscreen TV         75999

              Date
0    2/5/2019 3:00
1    2/5/2019 4:00
2    2/6/2019 5:00
3    2/6/2019 6:00
4   2/10/2019 7:00
5   2/11/2019 8:00
6   2/11/2019 9:00
7  2/20/2019 10:00
8  2/20/2019 11:00
/content/sample_data/daniel/mar_sales.csv
   Order_Id Customer_Name  Customer_Id              Product_Name  \
0      1221        Shahid           20  Apple Airpods Headphones
1      1222       Sumanth           22           ThinkPad Laptop
2      1223       Sumanth           22           ThinkPad Laptop
3      1224        Partha            8        LG Washing Machine
4      1225       Karteek            4        LG Washing Machine
5      1226  Jaya Chandra           21  Apple Airpods Headphones
6      1227    Chaithanya           14              20in Monitor
7      1228         Kedar            2                 iPhone 11
8      1229        Balaji           12  Apple Airpods Headphones

   Product_Cost            Date
0         65000   3/7/2019 6:00
1         59000   3/7/2019 7:00
2         55999   3/7/2019 8:00
3         63999   3/7/2019 9:00
4         50000  3/8/2019 10:00
5         75000  3/8/2019 11:00
6         65999  3/9/2019 12:00
7         60000  3/9/2019 13:00
8         60000  3/9/2019 14:00

In Real-time for loops are not being used

We will use list comprehension syntax in real time.

all_dfs = [p1, p2]
all_dfs = [variable, for loop]

all 12 files will be printed

In [16]:
all_dfs = [pd.read_csv(files)  for files in alll_files]
print(all_dfs)

[   Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1914       Karteek            4        27in FHD Monitor         65000
1      1915    Nireekshan            1                iPhone 9         65000
2      1916     Madhurima            7        27in FHD Monitor         65999
3      1917        Balaji           12               iPhone 11         59000
4      1918        Partha            8  34in Ultrawide Monitor         61000
5      1919        Shahid           20                iPhone 8         65999
6      1920       Sumanth           22               LG Mobile         69000
7      1921       Lavanya           16  LG ThinQ Refrigerator          63000
8      1922   Mallikarjun           13  34in Ultrawide Monitor         50000

               Date
0    10/7/2019 3:00
1    10/7/2019 4:00
2    10/8/2019 5:00
3    10/8/2019 6:00
4    10/9/2019 7:00
5    10/9/2019 8:00
6   10/11/2019 9:00
7  10/11/2019 10:00
8  10/12/2019 11:00  ,    Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1716       Karteek            4                iPhone 8         60000
1      1717  Jaya Chandra           21           Flatscreen TV         63000
2      1718       Sumanth           22               LG Mobile         51999
3      1719        Siddhu           18               iPhone 11         59000
4      1720         Kedar            2  34in Ultrawide Monitor         55000
5      1721       Sumanth           22               LG Mobile         75000
6      1722         Vijay            9      Macbook Pro Laptop         50000
7      1723         Vijay            9           Flatscreen TV         51999
8      1724         Kedar            2               LG Mobile         65000

              Date
0  8/20/2019 21:00
1  8/20/2019 22:00
2  8/21/2019 23:00
3   8/30/2019 0:00
4   8/30/2019 1:00
5   8/30/2019 2:00
6   8/30/2019 3:00
7   8/30/2019 4:00
8   8/30/2019 5:00  ,    Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      2013        Daniel            6            Google Phone         63999
1      2014       Karteek            4  27in 4K Gaming Monitor         55999
2      2015        Siddhu           18  Samsung Galaxy S9 Plus         50000
3      2016        Partha            8            Google Phone         50000
4      2017         Kedar            2         ThinkPad Laptop         65000
5      2018        Daniel            6        27in FHD Monitor         75000
6      2019        Harsha            5  34in Ultrawide Monitor         55000
7      2020        Balaji           12               LG Mobile         50000
8      2021        Shahid           20                iPhone 9         55999

              Date
0   11/1/2019 6:00
1   11/1/2019 7:00
2   11/2/2019 8:00
3   11/2/2019 9:00
4  11/2/2019 10:00
5  11/2/2019 11:00
6  11/2/2019 12:00
7  11/2/2019 13:00
8  11/2/2019 14:00  ,    Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1320          Venu           23      LG ThinQ Refrigerator
1      1321  Jaya Chandra           21  Bose SoundSport Headphones
2      1322   Mallikarjun           13    Apple Airpods Headphones
3      1323        Siddhu           18      Samsung Galaxy S9 Plus
4      1324        Daniel            6                    iPhone 8
5      1325        Harsha            5                   LG Mobile
6      1326        Siddhu           18                   iPhone 7s
7      1327         Shafi           25        Apple iPad 10.2-inch
8      1328   Mallikarjun           13            27in FHD Monitor

   Product_Cost             Date
0         55000   4/11/2019 9:00
1         63000  4/13/2019 10:00
2         69999  4/13/2019 11:00
3         55000  4/14/2019 12:00
4         55000  4/15/2019 13:00
5         50000  4/15/2019 14:00
6         69999  4/16/2019 15:00
7         50000  4/16/2019 16:00
8         63999  4/16/2019 17:00  ,    Order_Id Customer_Name  Customer_Id              Product_Name  \
0      1518    Chaithanya           14        LG Washing Machine
1      1519         Shafi           25                 iPhone 7s
2      1520       Neelima           19              Google Phone
3      1521         Tarun           11  Apple Airpods Headphones
4      1522   Mallikarjun           13          27in FHD Monitor
5      1523        Siddhu           18                 iPhone 7s
6      1524    Nireekshan            1             Flatscreen TV
7      1525        Harsha            5                 LG Mobile
8      1526          Venu           23        Samsung Galaxy S20

   Product_Cost             Date
0         59000   6/1/2019 15:00
1         55999   6/1/2019 16:00
2         65999   6/2/2019 17:00
3         59000   6/2/2019 18:00
4         75999   6/3/2019 19:00
5         55999  6/26/2019 20:00
6         63000  6/26/2019 21:00
7         59000  6/26/2019 22:00
8         55000  6/26/2019 23:00  ,    Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1023         Venki           15            27in FHD Monitor
1      1024    Chaithanya           14                   iPhone 11
2      1025        Shahid           20  Bose SoundSport Headphones
3      1026         Veeru            3        Apple iPad 10.2-inch
4      1027          Venu           23                Google Phone
5      1028        Daniel            6      Samsung Galaxy S9 Plus
6      1029          Venu           23                   iPhone 11
7      1030         Shafi           25            27in FHD Monitor
8      1031         Kedar            2                20in Monitor

   Product_Cost           Date
0         59000  1/1/2019 0:00
1         69000  1/1/2019 1:00
2         65999  1/2/2019 2:00
3         63999  1/2/2019 3:00
4         63999  1/2/2019 4:00
5         63999  1/2/2019 5:00
6         61000  1/3/2019 6:00
7         63000  1/3/2019 7:00
8         55999  1/3/2019 8:00  ,    Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1617        Siddhu           18      Samsung Galaxy S20         63999
1      1618       Pradhan           17         ThinkPad Laptop         60000
2      1619   Mallikarjun           13               iPhone 11         55999
3      1620    Nireekshan            1        27in FHD Monitor         75000
4      1621        Daniel            6                iPhone 9         50000
5      1622        Partha            8                iPhone 9         65000
6      1623         Veeru            3                iPhone 9         69999
7      1624         Venki           15                iPhone 8         55000
8      1625       Sumanth           22  Samsung Galaxy S9 Plus         75000

              Date
0  7/25/2019 18:00
1  7/25/2019 19:00
2  7/25/2019 20:00
3  7/25/2019 21:00
4  7/25/2019 22:00
5  7/25/2019 23:00
6   7/26/2019 0:00
7   7/26/2019 1:00
8   7/26/2019 2:00  ,    Order_Id Customer_Name  Customer_Id              Product_Name  \
0      2112         Mohan           24                  iPhone 8
1      2113    Chaithanya           14  Apple Airpods Headphones
2      2114       Lavanya           16        Macbook Pro Laptop
3      2115        Shahid           20        LG Washing Machine
4      2116         Vinay           10                 LG Mobile
5      2117        Shahid           20      Apple iPad 10.2-inch
6      2118        Shahid           20                  iPhone 9
7      2119    Chaithanya           14             Flatscreen TV
8      2120       Neelima           19    34in Ultrawide Monitor

   Product_Cost              Date
0         50000   12/15/2019 9:00
1         50000  12/15/2019 10:00
2         61000  12/15/2019 11:00
3         55999  12/16/2019 12:00
4         75999  12/16/2019 13:00
5         61000  12/17/2019 14:00
6         63999  12/18/2019 15:00
7         69999  12/19/2019 16:00
8         51999  12/19/2019 17:00  ,    Order_Id Customer_Name  Customer_Id                Product_Name  \
0      1419    Nireekshan            1                20in Monitor
1      1420         Veeru            3             ThinkPad Laptop
2      1421   Mallikarjun           13               Flatscreen TV
3      1422         Shafi           25                   iPhone 11
4      1423        Partha            8          Samsung Galaxy S20
5      1424       Karteek            4                Google Phone
6      1425        Siddhu           18          Macbook Pro Laptop
7      1426         Shafi           25          Macbook Pro Laptop
8      1427       Karteek            4  Bose SoundSport Headphones

   Product_Cost             Date
0         55000  5/17/2019 12:00
1         55000  5/17/2019 13:00
2         55000  5/18/2019 14:00
3         65000  5/18/2019 15:00
4         55000  5/19/2019 16:00
5         63999  5/19/2019 17:00
6         50000  5/20/2019 18:00
7         65000  5/21/2019 19:00
8         65000  5/22/2019 20:00  ,    Order_Id Customer_Name  Customer_Id            Product_Name  Product_Cost  \
0      1122     Madhurima            7               iPhone 11         63000
1      1123        Balaji           12            Google Phone         65999
2      1124  Jaya Chandra           21      LG Washing Machine         75999
3      1125         Vinay           10        27in FHD Monitor         69000
4      1126  Jaya Chandra           21                iPhone 8         63999
5      1127          Venu           23                iPhone 9         51999
6      1128       Sumanth           22  Samsung Galaxy S9 Plus         55000
7      1129       Karteek            4  27in 4K Gaming Monitor         63999
8      1130  Jaya Chandra           21           Flatscreen TV         75999

              Date
0    2/5/2019 3:00
1    2/5/2019 4:00
2    2/6/2019 5:00
3    2/6/2019 6:00
4   2/10/2019 7:00
5   2/11/2019 8:00
6   2/11/2019 9:00
7  2/20/2019 10:00
8  2/20/2019 11:00  ,    Order_Id Customer_Name  Customer_Id              Product_Name  \
0      1221        Shahid           20  Apple Airpods Headphones
1      1222       Sumanth           22           ThinkPad Laptop
2      1223       Sumanth           22           ThinkPad Laptop
3      1224        Partha            8        LG Washing Machine
4      1225       Karteek            4        LG Washing Machine
5      1226  Jaya Chandra           21  Apple Airpods Headphones
6      1227    Chaithanya           14              20in Monitor
7      1228         Kedar            2                 iPhone 11
8      1229        Balaji           12  Apple Airpods Headphones

   Product_Cost            Date
0         65000   3/7/2019 6:00
1         59000   3/7/2019 7:00
2         55999   3/7/2019 8:00
3         63999   3/7/2019 9:00
4         50000  3/8/2019 10:00
5         75000  3/8/2019 11:00
6         65999  3/9/2019 12:00
7         60000  3/9/2019 13:00
8         60000  3/9/2019 14:00  ]

In [17]:
# Now we shall concatenate all the files.
all_year_files = pd.concat(all_dfs, ignore_index = True)
all_year_files

,Order_Id,Customer_Name,Customer_Id,Product_Name,Product_Cost,Date
0,1914,Karteek,4,27in FHD Monitor,65000,10/7/2019 3:00
1,1915,Nireekshan,1,iPhone 9,65000,10/7/2019 4:00
2,1916,Madhurima,7,27in FHD Monitor,65999,10/8/2019 5:00
3,1917,Balaji,12,iPhone 11,59000,10/8/2019 6:00
4,1918,Partha,8,34in Ultrawide Monitor,61000,10/9/2019 7:00
...,...,...,...,...,...,...
94,1225,Karteek,4,LG Washing Machine,50000,3/8/2019 10:00
95,1226,Jaya Chandra,21,Apple Airpods Headphones,75000,3/8/2019 11:00
96,1227,Chaithanya,14,20in Monitor,65999,3/9/2019 12:00
97,1228,Kedar,2,iPhone 11,60000,3/9/2019 13:00
98,1229,Balaji,12,Apple Airpods Headphones,60000,3/9/2019 14:00

In [18]:
# To get this concatenated DataFrame as a physical file.
all_year_files.to_csv('year.csv')